import * as THREE from 'three';
import {mergeGeometries} from 'three/examples/jsm/utils/BufferGeometryUtils.js';
import {unitsPerSecondToKmh} from '../core/world-units.js';
import {cloneReviewActor,applyReviewPose,reviewFrame} from './melee-recording.js';

// A preparation dimension owns its geometry and temporarily mounts native world
// collision collections. The desert collections are retained, never rebuilt.
export class ThreatRoom {
 constructor(g,members){
  this.g=g;this.members=members;this.active=true;this.peak=0;this.group=new THREE.Group();this.group.name='white-threat-room';
  const w=g.world;this.saved={entities:g.entities,cover:w.cover,interiors:w.interiors,rocks:w.rocks,arena:w.ARENA,height:w.heightAt,water:w.waterAt,fog:g.scene.fog,background:g.scene.background};
  this.lightLevels=[];for(const o of g.scene.children)if(o.isLight&&!o.isPointLight){this.lightLevels.push([o,o.intensity]);o.intensity*=.35;}this.bloom=g.world.bloom?.strength;if(g.world.bloom)g.world.bloom.strength=.12;
  this.hidden=[];for(const o of g.scene.children)if(!o.isLight&&!o.isPoints&&!members.some(f=>f.obj===o)){this.hidden.push([o,o.visible]);o.visible=false;}
  g.entities=members.slice();w.cover=[];w.interiors=[];w.rocks=[];w.ARENA=310;w.heightAt=()=>0;w.waterAt=()=>0;g.scene.fog=new THREE.FogExp2(0xc7d4df,.00035);g.scene.background=new THREE.Color(0xdce5eb);
  this.worldLists={};for(const key of ["cars","planes","treeSpots","coverAll"]){this.worldLists[key]=w[key];w[key]=[];}this.worldFunctions={};for(const key of ["crater","flattenGrass"]){this.worldFunctions[key]=w[key];w[key]=()=>{};}
  this.savedShots=g.projectiles.list;g.projectiles.list=[];this.savedMinions=g.minions;g.minions=[];this.savedConstructs=g.constructs;g.constructs=[];
  g.scene.add(this.group);g._threatRoom=this;w._threatRoom=this;
  const white=new THREE.MeshStandardMaterial({color:0xdde5e9,roughness:.78}),dark=new THREE.MeshStandardMaterial({color:0x4c5962,roughness:.8}),edge=new THREE.MeshStandardMaterial({color:0xaebdc7,roughness:.65}),light=new THREE.MeshBasicMaterial({color:0xe7faff});
  const stripeCanvas=document.createElement('canvas');stripeCanvas.width=128;stripeCanvas.height=128;const sc=stripeCanvas.getContext('2d');sc.fillStyle='#e4bb39';sc.fillRect(0,0,128,128);sc.fillStyle='#303d46';for(let x=-128;x<256;x+=64){sc.beginPath();sc.moveTo(x,0);sc.lineTo(x+32,0);sc.lineTo(x+160,128);sc.lineTo(x+128,128);sc.fill();}const stripeTex=new THREE.CanvasTexture(stripeCanvas);stripeTex.colorSpace=THREE.SRGBColorSpace;stripeTex.wrapS=stripeTex.wrapT=THREE.RepeatWrapping;const stripe=new THREE.MeshStandardMaterial({map:stripeTex,roughness:.9});
  const batches=new Map();const box=(x,y,z,sx,sy,sz,mat=white,solid=false)=>{const geo=new THREE.BoxGeometry(sx,sy,sz);geo.translate(x,y,z);if(!batches.has(mat))batches.set(mat,[]);batches.get(mat).push(geo);if(solid)w.cover.push({x,z,hx:sx/2,hz:sz/2,bottom:y-sy/2,top:y+sy/2,h:y+sy/2,finiteBuilding:true,threatRoom:true});};
  box(0,-2,0,620,4,620,white);box(0,302,0,620,4,620,white,true);
  for(const x of [-306,306])box(x,150,0,12,300,620,white,true);for(const z of [-306,306])box(0,150,z,620,300,12,white,true);
  // Floor panel joints, central runway and measured flight lanes.
  for(let n=-300;n<=300;n+=30){box(n,.03,0,.22,.06,600,edge);box(0,.035,n,600,.06,.22,edge);}box(0,.06,0,40,.08,540,dark);
  for(let z=-270;z<=270;z+=30){box(-23,.12,z,3,.12,12,stripe);box(23,.12,z,3,.12,12,stripe);}
  for(let x=-270;x<=270;x+=60){box(x,150,-299,1,300,.6,edge);box(x,150,299,1,300,.6,edge);box(x,150,-298,1.5,286,1,light);}for(let z=-270;z<=270;z+=60){box(-299,150,z,.6,300,1,edge);box(299,150,z,.6,300,1,edge);box(298,150,z,1,286,1.5,light);}
  // Two side galleries leave a broad, clear central flight volume.
  for(const x of [-250,250])for(const y of [48,104]){box(x,y,-60,82,4,420,white,true);box(x,y-2.2,-60,65,.5,400,light);for(const z of [-240,-120,0,120])box(x,y/2,z,9,y,9,dark,true);const inside=x<0?x+40:x-40;box(inside,y+9,-60,1,1,390,dark);box(inside,y+5,-60,1,1,390,dark);for(let z=-250;z<140;z+=20)box(inside,y+5,z,1,10,1,dark);}
  // Walkable broad stairs to the first gallery, with a striped edge.
  for(let i=0;i<48;i++){box(-245,(i+1)/2,245-i*2.2,60,i+1,2.25,white,true);box(-215,(i+1)+.08,245-i*2.2,2,.15,2.25,stripe);}
  for(const [x,z]of [[-85,-130],[85,-130],[-100,65],[100,65]]){box(x,9,z,24,18,10,white,true);box(x-11,9,z+.1,2,18,10.4,stripe);}
  box(0,76,-205,100,4,70,white,true);box(0,73.8,-205,96,.5,66,light);for(const x of [-48,48])box(x,187,-205,1.3,220,1.3,dark);box(0,79,-171,100,3,2,stripe);
  for(let y=30;y<300;y+=30){box(0,y,-299,600,.25,.4,edge);box(0,y,299,600,.25,.4,edge);box(-299,y,0,.4,.25,600,edge);box(299,y,0,.4,.25,600,edge);}
  for(const x of [-140,140]){box(x,18,-299,38,36,2,dark);box(x,37,-297,42,1,1,light);box(x,18,-297,.6,36,.8,edge);}
  box(0,87,-205,40,18,32,dark);box(0,97,-205,44,2,36,stripe);
  for(const [mat,geos]of batches){const mesh=new THREE.Mesh(mergeGeometries(geos),mat);mesh.receiveShadow=true;mesh.castShadow=mat!==light;this.group.add(mesh);geos.forEach(geo=>geo.dispose());}
  const shadowCanvas=document.createElement('canvas');shadowCanvas.width=shadowCanvas.height=128;const sh=shadowCanvas.getContext('2d'),gradient=sh.createRadialGradient(64,64,8,64,64,64);gradient.addColorStop(0,'rgba(33,48,60,.28)');gradient.addColorStop(.5,'rgba(33,48,60,.12)');gradient.addColorStop(1,'rgba(33,48,60,0)');sh.fillStyle=gradient;sh.fillRect(0,0,128,128);const shadowTexture=new THREE.CanvasTexture(shadowCanvas),shadowMaterial=new THREE.MeshBasicMaterial({map:shadowTexture,transparent:true,depthWrite:false});const shadows=[];for(const c of w.cover)if(c.bottom<=0&&c.top<150){const geo=new THREE.PlaneGeometry(c.hx*3+12,c.hz*3+12);geo.rotateX(-Math.PI/2);geo.translate(c.x,.13,c.z);shadows.push(geo);}if(shadows.length){this.group.add(new THREE.Mesh(mergeGeometries(shadows),shadowMaterial));shadows.forEach(s=>s.dispose());}
  const fill=new THREE.HemisphereLight(0xf4fbff,0xa5b3c2,.85);this.group.add(fill);
  this.label('THREAT ROOM',0,164,-297,190,32);this.label('SIM 01  /  TRAIN · ADAPT · IMPROVE',0,143,-298,160,12);
  this.label('PORTAL  /  DESERT',0,32,170,68,8);this.label('FLIGHT LANE  /  540u',0,.2,-280,80,9,-Math.PI/2);
  this.speed=this.screen(-85,26,115,65,34);this.tv=this.screen(85,27,115,68,38);this.label('REPLAY  /  E TO REVIEW',85,5,115,68,5);
  this.replayScene=new THREE.Scene();this.replayScene.background=new THREE.Color(0x18242f);this.replayScene.add(new THREE.HemisphereLight(0xffffff,0x71818c,3));this.replayCamera=new THREE.PerspectiveCamera(45,16/9,.1,2000);this.target=new THREE.WebGLRenderTarget(512,288);this.replayTime=0;
 }
 label(text,x,y,z,width,height,rx=0){const c=document.createElement('canvas');c.width=1024;c.height=128;const ctx=c.getContext('2d');ctx.fillStyle='#52636e';ctx.font='600 52px sans-serif';ctx.textAlign='center';ctx.fillText(text,512,80);const tex=new THREE.CanvasTexture(c);const m=new THREE.Mesh(new THREE.PlaneGeometry(width,height),new THREE.MeshBasicMaterial({map:tex,transparent:true,side:THREE.DoubleSide,depthWrite:false}));m.position.set(x,y,z);m.rotation.x=rx;this.group.add(m);return m;}
 screen(x,y,z,width,height){const canvas=document.createElement('canvas');canvas.width=768;canvas.height=432;const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;const mesh=new THREE.Mesh(new THREE.PlaneGeometry(width,height),new THREE.MeshBasicMaterial({map:texture}));mesh.position.set(x,y,z);this.group.add(mesh);return {canvas,texture,mesh};}
 update(dt){if(!this.active)return;for(const [o]of this.hidden)o.visible=false;const g=this.g,speed=unitsPerSecondToKmh(g.player.vel.length());if(g.player.alive&&g.player.flying&&g.player.launchT<=0)this.peak=Math.max(this.peak,speed);this.clock=(this.clock||0)+dt;if(this.clock<.1)return;this.clock=0;
  const ctx=this.speed.canvas.getContext('2d');ctx.fillStyle='#152633';ctx.fillRect(0,0,768,432);ctx.fillStyle='#8bdfff';ctx.font='28px sans-serif';ctx.fillText('FLIGHT TELEMETRY',40,54);ctx.fillStyle='#f3fbff';ctx.font='bold 96px sans-serif';ctx.fillText(Math.round(speed)+' km/h',40,184);ctx.font='40px sans-serif';ctx.fillText('TOP  '+Math.round(this.peak)+' km/h',40,267);ctx.font='25px sans-serif';ctx.fillText('ALTITUDE  '+Math.round(g.player.pos.y)+'u',40,345);this.speed.texture.needsUpdate=true;
  const recording=g.ms.threatLab?.meleeTrial?.recording;if(recording?.frames.length>2){if(this.source!==recording.actors){this.copies?.forEach(c=>c.dispose());this.source=recording.actors;this.copies=recording.actors.map(a=>cloneReviewActor(a.template.model));this.copies.forEach(c=>this.replayScene.add(c.model));this.replayTime=recording.frames[0].time;}this.replayTime+=.05;const start=recording.frames[0].time,end=recording.frames.at(-1).time;if(this.replayTime<start||this.replayTime>end)this.replayTime=start;const {a,b,mix}=reviewFrame(recording.frames,this.replayTime);this.copies.forEach((c,i)=>applyReviewPose(c.nodes,a.actors[i].pose,b.actors[i].pose,mix));const center=this.copies[0].model.position.clone().add(this.copies[1].model.position).multiplyScalar(.5);center.y+=6;const distance=Math.max(28,this.copies[0].model.position.distanceTo(this.copies[1].model.position)*1.2);this.replayCamera.position.copy(center).add(new THREE.Vector3(distance*.8,distance*.4,distance));this.replayCamera.lookAt(center);const renderer=g.world.renderer,prior=renderer.getRenderTarget();renderer.setRenderTarget(this.target);renderer.render(this.replayScene,this.replayCamera);renderer.setRenderTarget(prior);this.tv.mesh.material.map=this.target.texture;
  }else{const c=this.tv.canvas.getContext('2d');c.fillStyle='#152633';c.fillRect(0,0,768,432);c.fillStyle='#dfeaf0';c.font='bold 45px sans-serif';c.fillText('COMBAT REPLAY',55,140);c.font='28px sans-serif';c.fillText('Start a drill to capture an exchange.',55,225);c.fillText('Recorded poses · half-speed review',55,300);this.tv.texture.needsUpdate=true;this.tv.mesh.material.map=this.tv.texture;}
 }
 leave(){if(!this.active)return;this.active=false;const g=this.g,w=g.world;for(const p of g.projectiles.list)p._dispose?.(g);for(const o of [...g.minions,...g.constructs])o._dispose?.(g);g.projectiles.list=this.savedShots;g.minions=this.savedMinions;g.constructs=this.savedConstructs;g.entities=[...new Set([...this.saved.entities,...this.members])];for(const key of ['cover','interiors','rocks'])w[key]=this.saved[key];for(const [key,value]of Object.entries(this.worldLists))w[key]=value;for(const [key,value]of Object.entries(this.worldFunctions))w[key]=value;w.ARENA=this.saved.arena;w.heightAt=this.saved.height;w.waterAt=this.saved.water;g.scene.fog=this.saved.fog;g.scene.background=this.saved.background;for(const [o,v]of this.hidden)o.visible=v;for(const [o,v]of this.lightLevels)o.intensity=v;if(w.bloom)w.bloom.strength=this.bloom;this.group.visible=false;g._threatRoom=null;w._threatRoom=null;}
 dispose(){this.leave();this.copies?.forEach(c=>c.dispose());this.target.dispose();const resources=new Set();this.group.traverse(o=>{if(o.geometry)resources.add(o.geometry);if(o.material){resources.add(o.material);if(o.material.map)resources.add(o.material.map);}});resources.forEach(r=>r.dispose());this.group.removeFromParent();}
}
