import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {Fighter} from '../engine/entity.js';
import {updateLimbSurfaces} from '../engine/hero-limb-surface.js';
import {updateHeroSkin} from '../engine/hero-skin.js';
import {ROSTER} from '../data/characters.js';
import {buildAnimationCatalog,resolveAnimationClip} from '../data/animation-catalog.js';
import {samplePoseFrame,applyAuthoredPose} from '../engine/authored-pose.js';
import '../styles/tokens.css';
import './animation-page.css';
const catalog=buildAnimationCatalog();
document.body.innerHTML=`<header><div><p class="brand">POWERWORLD / CONTENT STUDIO</p><h1>Animation Library</h1></div><nav><a href="studio.html">Character Studio</a><a href="sound-library.html">Sound Library</a><a href="powerworld.html">Play</a></nav></header><main><aside class="catalog"><label for="search">Find an animation</label><input id="search" type="search" placeholder="Search name or source take"><label for="category">Move family</label><select id="category"><option value="">All families</option></select><p id="count" role="status"></p><div id="clips"></div></aside><section class="viewer"><div class="stagebar"><div><span class="eyebrow">AUTHORED CLIP PREVIEW</span><h2 id="clip-title"></h2></div><label>Character <select id="character"></select></label></div><div id="stage"><div class="camera" aria-label="Camera angles"><button data-view="front">Front</button><button data-view="side">Side</button><button data-view="back">Back</button><button data-view="overhead">Above</button></div><span class="stage-note">Drag to orbit · scroll to zoom</span></div><div class="transport"><button id="play">Pause</button><button id="step" title="Pause and advance one source frame">Frame +</button><button id="restart">Restart</button><label>Speed <select id="speed"><option value=".25">¼×</option><option value=".5">½×</option><option value="1" selected>1×</option></select></label><output id="clock"></output><input id="scrub" aria-label="Animation position" type="range" min="0" max="1" step=".001" value="0"></div><p class="disclosure">Pose preview only. Gameplay controls approach, hit detection, damage and recovery timing.</p></section><aside class="details"><h2>Clip details</h2><dl id="metadata"></dl><h3>Validation</h3><div id="validation"></div><button id="export">Export catalog</button><p class="disclosure">Character assignments and audio links are not audited yet. Editing and procedural families are coming next.</p></aside></main>`;
const $=s=>document.querySelector(s),select=$('#character');
for(const d of ROSTER)select.add(new Option(d.name,d.id));select.value='vega';
for(const name of new Set(catalog.entries.map(e=>e.category)))$('#category').add(new Option(name,name));
let entry=catalog.entries[0],clip=resolveAnimationClip(entry.id),time=0,playing=true,rate=1,fighter,base=[];
const scene=new T.Scene();scene.background=new T.Color('#171c20');
const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;
$('#stage').prepend(renderer.domElement);const camera=new T.PerspectiveCamera(38,1,.1,500),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=8;controls.maxDistance=100;
scene.add(new T.HemisphereLight('#edf4ff','#665342',1.4));const key=new T.DirectionalLight('#fff1d5',3);key.position.set(-15,25,18);scene.add(key);const rim=new T.DirectionalLight('#a6d6ef',1.3);rim.position.set(12,18,-15);scene.add(rim);
const floor=new T.Mesh(new T.CircleGeometry(100,64),new T.MeshStandardMaterial({color:'#252a2b',roughness:1}));floor.rotation.x=-Math.PI/2;floor.position.y=-.04;scene.add(floor);
const frame=new Float64Array(45);let center=new T.Vector3(),distance=30;
function view(name){const dirs={front:[0,.12,1],side:[1,.12,0],back:[0,.12,-1],overhead:[.01,1,.01]};camera.position.copy(center).add(new T.Vector3(...dirs[name]).normalize().multiplyScalar(distance));controls.target.copy(center);controls.update();}
function character(){if(fighter){scene.remove(fighter.obj);fighter.dispose();}const def=ROSTER.find(d=>d.id===select.value)||ROSTER[0];fighter=new Fighter(def,{rimK:.14});scene.add(fighter.obj);fighter.obj.updateMatrixWorld(true);base=[];fighter.obj.traverse(o=>base.push({o,p:o.position.clone(),q:o.quaternion.clone(),s:o.scale.clone()}));const box=new T.Box3().setFromObject(fighter.obj);box.getCenter(center);center.y=Math.max(4,center.y);distance=Math.max(18,box.getSize(new T.Vector3()).y*1.9);view('front');}
function list(){const q=$('#search').value.toLowerCase(),category=$('#category').value,entries=catalog.entries.filter(e=>(!category||e.category===category)&&`${e.label} ${e.take}`.toLowerCase().includes(q));$('#clips').replaceChildren();$('#count').textContent=`${entries.length} of ${catalog.entries.length} clips`;for(const e of entries){const b=document.createElement('button');b.className='clip';b.setAttribute('aria-pressed',String(e.id===entry.id));const strong=document.createElement('strong'),small=document.createElement('small');strong.textContent=e.label;small.textContent=`${e.category} · ${e.duration.toFixed(2)}s`;b.append(strong,small);b.onclick=()=>choose(e);$('#clips').append(b);}if(!entries.length)$('#clips').textContent='No matching animations. Try another search.';}
function choose(e){entry=e;clip=resolveAnimationClip(e.id);time=0;$('#clip-title').textContent=e.label;$('#metadata').replaceChildren();for(const [label,value] of [['Source take',e.take],['Duration',`${e.duration.toFixed(3)} seconds`],['Frames',e.frames],['Contact window',e.contact?`${e.contact.start.toFixed(3)}–${e.contact.end.toFixed(3)}s`:'Not a strike'],['Source',e.source?.author||'Unknown'],['Runtime',e.runtime]]){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;$('#metadata').append(dt,dd);}$('#validation').textContent=[e.issues.length?e.issues.join(', '):'Pose data valid',...e.warnings].join(' · ');list();}
$('#search').oninput=list;$('#category').onchange=list;select.onchange=character;
function pause(value){playing=value;$('#play').textContent=playing?'Pause':'Play';}
$('#play').onclick=()=>pause(!playing);$('#restart').onclick=()=>{time=0;};$('#step').onclick=()=>{pause(false);time=Math.min(clip.duration,time+1/(entry.source?.sampleRate||60));};$('#speed').onchange=e=>rate=Number(e.target.value);$('#scrub').oninput=e=>{pause(false);time=Number(e.target.value)*clip.duration;};
for(const b of document.querySelectorAll('[data-view]'))b.onclick=()=>view(b.dataset.view);
$('#export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(catalog,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='powerworld-animation-catalog.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
new ResizeObserver(()=>{const host=$('#stage');renderer.setSize(host.clientWidth,host.clientHeight);camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();}).observe($('#stage'));
character();choose(entry);let last=performance.now();function render(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(playing)time=(time+dt*rate)%clip.duration;for(const b of base){b.o.position.copy(b.p);b.o.quaternion.copy(b.q);b.o.scale.copy(b.s);}if(fighter.parts.rig){samplePoseFrame(clip,time/clip.duration,frame,false);applyAuthoredPose(fighter,frame,1,{legs:true,hips:true,support:true});updateLimbSurfaces(fighter.parts);updateHeroSkin(fighter.parts);}$('#scrub').value=String(time/clip.duration);$('#clock').textContent=`${time.toFixed(2)} / ${clip.duration.toFixed(2)}s`;controls.update();renderer.render(scene,camera);requestAnimationFrame(render);}requestAnimationFrame(render);
window.animationLibrary={get selected(){return entry.id;},get time(){return time;},get playing(){return playing;},get hasRig(){return !!fighter.parts.rig;}};
