import {animationFamily} from '../data/animation-families.js';
import {createAnimationEquipment,ANIMATION_EQUIPMENT_CHOICES,recommendationForTake} from './animation-equipment.js';
import {animationReview} from './animation-review.js';
import {advancePreview,previewOffset,STUDY_CONTEXT} from './animation-playback.js';
import {loadModularMotionBank} from '../engine/modular-motions.js';
import {loadPaidMotionBank} from '../engine/paid-motion-runtime.js';
import {characterStudyCatalog} from '../engine/character-study-catalog.js';
import {createModularActor,modularAsset} from '../engine/modular-character.js';
import {applyModularRecipe,MODULAR_RECIPES} from '../engine/modular-costume.js';
import {poseHoldPair,clearHoldPreview} from './paired-hold-preview.js';
import {mountFavorites} from './library-favorites.js';
import authoringGuide from '../../docs/gameplay/ANIMATION_CONTENT_WORKER_HANDOFF.md?raw';
import {applyProfile,loadProfile,saveProfile,profileFromDef} from './studio-profile.js';
import {markerDraft,clipWithMarkers,readMarkerDrafts,saveMarkerDraft,revertMarkerDraft} from './animation-drafts.js';
import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {Fighter} from '../engine/entity.js';
import {updateLimbSurfaces} from '../engine/hero-limb-surface.js';
import {updateHeroSkin} from '../engine/hero-skin.js';
import {ROSTER} from '../data/characters.js';
import {buildAnimationCatalog,resolveAnimationClip,animationAttention} from '../data/animation-catalog.js';
import {samplePoseFrame,applyAuthoredPose} from '../engine/authored-pose.js';
import '../styles/tokens.css';
import './animation-page.css';
const catalog=buildAnimationCatalog();catalog.entries=[...catalog.entries,...catalog.procedural];
document.body.innerHTML=`<header><div><p class="brand">POWERWORLD / CONTENT STUDIO</p><h1>Animation Library</h1></div><nav><a href="studio.html">Character Studio</a><a href="sound-library.html">Sound Library</a><a href="powerworld.html">Play</a></nav></header><main><aside class="catalog"><label for="search">Find an animation</label><input id="search" type="search" placeholder="Search name or source take"><label for="category">Move family</label><select id="category"><option value="">All families</option></select><p id="count" role="status"></p><div id="clips"></div></aside><section class="viewer"><div class="stagebar"><div><span class="eyebrow">AUTHORED CLIP PREVIEW</span><h2 id="clip-title"></h2></div><label>Character <select id="character"></select></label></div><div id="stage"><div class="camera" aria-label="Camera angles"><button data-view="front">Front</button><button data-view="side">Side</button><button data-view="back">Back</button><button data-view="overhead">Above</button></div><span class="stage-note">Drag to orbit · scroll to zoom</span></div><div class="transport"><button id="play">Pause</button><button id="step" title="Pause and advance one source frame">Frame +</button><button id="restart">Restart</button><label><input id="loop" type="checkbox">Repeat clip</label><label>Speed <select id="speed"><option value=".25">¼×</option><option value=".5">½×</option><option value="1" selected>1×</option></select></label><output id="clock"></output><input id="scrub" aria-label="Animation position" type="range" min="0" max="1" step=".001" value="0"></div><p id="preview-help" class="disclosure" role="status">Choose a move to play it. Pause and use Frame + to inspect contact.</p></section><aside class="details"><h2>Clip details</h2><dl id="metadata"></dl><h3>Your review</h3><p id="user-review" class="disclosure"></p><h3>Validation</h3><div id="validation"></div><section id="marker-editor"><h3>Contact markers</h3><p class="disclosure">Source clip time, in seconds. Saved drafts do not change live combat.</p><label>Start <input id="marker-start" type="number" min="0" step=".001"></label><label>End <input id="marker-end" type="number" min="0" step=".001"></label><button id="marker-preview">Preview contact</button><button id="marker-save">Save draft</button><button id="marker-revert">Discard local draft</button><button id="marker-export">Export draft</button><button id="marker-assign">Assign to selected character</button><button id="marker-unassign">Remove character assignment</button><p id="marker-status" role="status"></p></section><button id="export">Export catalog</button><p class="disclosure">Assignments change source-pose timing for this strike. Paired holds use native procedural poses; their timing is reviewed in the Threat Room. Audio links and other procedural families remain to be integrated.</p></aside></main>`;
const $=s=>document.querySelector(s),select=$('#character');
const guideButton=document.createElement('button');guideButton.textContent='Download authoring guide';$('#export').after(guideButton);
guideButton.onclick=()=>{const url=URL.createObjectURL(new Blob([authoringGuide],{type:'text/markdown'})),a=document.createElement('a');a.href=url;a.download='powerworld-animation-authoring.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
for(const d of ROSTER)select.add(new Option(d.name,d.id));select.value='vega';
const receiverLabel=document.createElement('label');receiverLabel.textContent='Held character';const receiverSelect=document.createElement('select');receiverSelect.setAttribute('aria-label','Held character');for(const d of ROSTER)receiverSelect.add(new Option(d.name,d.id));receiverSelect.value='merc';receiverLabel.append(receiverSelect);receiverLabel.hidden=true;$('#marker-editor').before(receiverLabel);receiverSelect.onchange=()=>character();
for(const name of new Set(catalog.entries.map(e=>e.category)))$('#category').add(new Option(name,name));
const attentionLabel=document.createElement('label');attentionLabel.htmlFor='attention';attentionLabel.textContent='Authoring status';
const attentionSelect=document.createElement('select');attentionSelect.id='attention';
for(const [value,label]of [['','All statuses'],['any','Needs attention'],['invalid','Invalid / missing animation'],['motion','Motion needs review'],['audio-missing','Audio missing'],['audio-unverified','Audio not audited']])attentionSelect.add(new Option(label,value));
$('#category').after(attentionLabel,attentionSelect);
const requestedClip=new URL(location.href).searchParams.get('clip');
let fullActor=null;
let entry=catalog.entries.find(e=>e.id===requestedClip)||catalog.entries[0],clip=resolveAnimationClip(entry.id)||{duration:entry.duration},time=0,playing=true,rate=1,fighter,receiver,base=[];
const scene=new T.Scene();scene.background=new T.Color('#171c20');
const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;
$('#stage').prepend(renderer.domElement);const camera=new T.PerspectiveCamera(38,1,.1,500),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=8;controls.maxDistance=100;
scene.add(new T.HemisphereLight('#edf4ff','#665342',1.4));const key=new T.DirectionalLight('#fff1d5',3);key.position.set(-15,25,18);scene.add(key);const rim=new T.DirectionalLight('#a6d6ef',1.3);rim.position.set(12,18,-15);scene.add(rim);
const floor=new T.Mesh(new T.CircleGeometry(100,64),new T.MeshStandardMaterial({color:'#252a2b',roughness:1}));floor.rotation.x=-Math.PI/2;floor.position.y=-.04;scene.add(floor);
const frame=new Float64Array(45);let center=new T.Vector3(),distance=30,poseFocusRoot=null;
const focusLastPosition=new T.Vector3();
function view(name){const dirs={front:[0,.12,1],side:[1,.12,0],back:[0,.12,-1],overhead:[.01,1,.01]};camera.position.copy(center).add(new T.Vector3(...dirs[name]).normalize().multiplyScalar(distance));controls.target.copy(center);controls.update();}
// Inspect articulation close up, then return to the full illustrative trajectory.
// Camera following moves only the review camera; it never changes pose or physics.
const focusButton=document.createElement('button');focusButton.textContent='Inspect pose';
const trajectoryButton=document.createElement('button');trajectoryButton.textContent='Show trajectory';
$('.camera').append(focusButton,trajectoryButton);
const expandButton=document.createElement('button');expandButton.textContent='Expand preview';$('.stagebar').append(expandButton);
expandButton.onclick=()=>{const expanded=$('main').classList.toggle('preview-expanded');expandButton.textContent=expanded?'Exit expanded preview':'Expand preview';};
focusButton.onclick=()=>{
 const root=entry.kind==='modular'?fullActor?.actor:fighter?.obj;if(!root)return;
 root.updateMatrixWorld(true);const bounds=new T.Box3();
 root.traverseVisible(o=>{if(o.isMesh)bounds.expandByObject(o,true);});
 if(receiver?.obj.visible)receiver.obj.traverseVisible(o=>{if(o.isMesh)bounds.expandByObject(o,true);});
 if(bounds.isEmpty())return;
 const direction=camera.position.clone().sub(controls.target).normalize();
 bounds.getCenter(center);const size=bounds.getSize(new T.Vector3());
 distance=Math.max(8,size.length()*.55/Math.sin(T.MathUtils.degToRad(camera.fov/2)));
 camera.position.copy(center).addScaledVector(direction,distance);controls.target.copy(center);controls.update();
 poseFocusRoot=root;focusLastPosition.copy(root.position);
};
trajectoryButton.onclick=()=>{poseFocusRoot=null;center.set(0,STUDY_CONTEXT[entry.key]?12:6,0);distance=STUDY_CONTEXT[entry.key]?38:28;view('side');};
const appearanceNotice=document.createElement('p');appearanceNotice.id='appearance-status';appearanceNotice.className='disclosure';appearanceNotice.setAttribute('role','status');$('.stagebar').after(appearanceNotice);
const equipmentPanel=document.createElement('section');equipmentPanel.className='equipment-panel';
equipmentPanel.innerHTML='<h3>Preview equipment</h3><label>Weapon <select id="preview-weapon"></select></label><label>Weapon hand <select id="preview-hand"><option value="auto">Automatic</option><option value="right">Right</option><option value="left">Left</option></select></label><label>Shield <select id="preview-shield"><option value="auto">Automatic</option><option value="off">Off</option><option value="on">On</option></select></label><p id="equipment-status" class="disclosure" role="status"></p>';
$('#metadata').before(equipmentPanel);
for(const choice of ANIMATION_EQUIPMENT_CHOICES)$('#preview-weapon').add(new Option(choice==='auto'?'Automatic':choice[0].toUpperCase()+choice.slice(1),choice));
for(const [key,id]of [['weapon','preview-weapon'],['hand','preview-hand'],['shield','preview-shield']]){const control=$('#'+id),value=new URL(location.href).searchParams.get(key);if(value&&Array.from(control.options).some(o=>o.value===value))control.value=value;control.onchange=()=>{const url=new URL(location.href);url.searchParams.set(key,control.value);history.replaceState(null,'',url);};}
let equipment=null,equipmentActor=null,equipmentKey='';
function syncEquipment(){
 const actor=entry.kind==='modular'?fullActor?.actor:entry.kind==='procedural'?null:fighter?._modularCharacter?.actor;
 if(actor!==equipmentActor){equipment?.dispose();equipmentActor=actor;equipment=actor?createAnimationEquipment(actor):null;equipmentKey='';}
 const key=[entry.id,$('#preview-weapon').value,$('#preview-hand').value,$('#preview-shield').value].join('|');
 for(const control of equipmentPanel.querySelectorAll('select'))control.disabled=entry.kind==='procedural';
 if(!equipment){$('#equipment-status').textContent=entry.kind==='procedural'?'Paired holds reserve the hands. Review weapons with a single-character clip.':'Waiting for the current modular model.';return;}
 if(key!==equipmentKey){const shield=$('#preview-shield').value,state=equipment.set({weapon:$('#preview-weapon').value,hand:$('#preview-hand').value,shield:shield==='auto'?recommendationForTake(entry.key||entry.take).shield:shield==='on'},entry.key||entry.take);equipmentKey=key;$('#equipment-status').textContent=(state.weapon==='none'?(state.shield?'Shield · left hand. ':'No equipment selected. '):state.weapon+' · '+state.hand+' hand. ')+state.warning;}
 // Independent viewer actors: hide loadout props behind the chosen review prop.
 if(entry.kind!=='modular')for(const arm of [fighter.parts.armL,fighter.parts.armR]){arm?.traverse(o=>{if(o.userData.weaponKind)o.visible=false;});if(arm?.userData.shield)arm.userData.shield.visible=false;}
}
const appearanceSources=new Map();
function previewDefinition(id){const source=ROSTER.find(d=>d.id===id)||ROSTER[0];try{const profile=loadProfile(source.id);const def=profile?applyProfile(source,profile):source;appearanceSources.set(source.id,source.name+': '+(profile?'saved Studio appearance':'shipped appearance'));return def;}catch(error){appearanceSources.set(source.id,source.name+': saved profile could not load; showing shipped appearance. '+error.message);return source;}}
function appearanceStatus(){if(entry.kind==='modular'){appearanceNotice.textContent='Modular Vegas reference body · source-motion review · roster appearance selection resumes with other clips';return;}appearanceNotice.textContent=[appearanceSources.get(select.value),...(receiver?[appearanceSources.get(receiverSelect.value)]:[])].filter(Boolean).join(' · ');}
function makeReceiver(){receiver=new Fighter(previewDefinition(receiverSelect.value),{rimK:.14});scene.add(receiver.obj);poseHoldPair(fighter,receiver,0,entry.friendly,entry.holdMode);receiver.obj.traverse(o=>base.push({receiver:true,o,p:o.position.clone(),q:o.quaternion.clone(),s:o.scale.clone()}));center.z=1.65;distance=Math.max(distance,28);view('side');appearanceStatus();}
function character(){if(receiver){scene.remove(receiver.obj);receiver.dispose();receiver=null;}if(fighter){scene.remove(fighter.obj);fighter.dispose();}const def=previewDefinition(select.value);fighter=new Fighter(def,{rimK:.14});scene.add(fighter.obj);fighter.obj.updateMatrixWorld(true);base=[];fighter.obj.traverse(o=>base.push({o,p:o.position.clone(),q:o.quaternion.clone(),s:o.scale.clone()}));const box=new T.Box3().setFromObject(fighter.obj);box.getCenter(center);center.y=Math.max(4,center.y);distance=Math.max(18,box.getSize(new T.Vector3()).y*1.9);view('front');if(entry.kind==='procedural')makeReceiver();appearanceStatus();}
const favoritesHost=document.createElement('div');$('#category').after(favoritesHost);
const favorites=mountFavorites({host:favoritesHost,kind:'animations',selected:()=>entry.id,onChange:()=>list()});
function list(){favorites.sync();const q=$('#search').value.toLowerCase(),category=$('#category').value,entries=catalog.entries.filter(e=>favorites.matches(e.id)&&(!attentionSelect.value||animationAttention(e).some(b=>attentionSelect.value==='any'||b.kind===attentionSelect.value))&&(!category||e.category===category)&&`${e.label} ${e.take}`.toLowerCase().includes(q));$('#clips').replaceChildren();$('#count').textContent=`${entries.length} of ${catalog.entries.length} clips`;for(const e of entries){const b=document.createElement('button');b.className='clip';b.setAttribute('aria-pressed',String(e.id===entry.id));const strong=document.createElement('strong'),small=document.createElement('small');strong.textContent=e.label;small.textContent=`${e.category} · ${e.duration.toFixed(2)}s`;b.append(strong,small);for(const badge of animationAttention(e)){const tag=document.createElement('span');tag.className='authoring-badge';tag.dataset.kind=badge.kind;tag.textContent=badge.label;b.append(tag);}b.onclick=()=>choose(e);$('#clips').append(b);}if(!entries.length)$('#clips').textContent='No matching animations. Try another search.';}
function choose(e){poseFocusRoot=null;select.disabled=e.kind==='modular';if(fullActor)fullActor.actor.visible=e.kind==='modular';if(fighter)fighter.obj.visible=e.kind!=='modular';base=base.filter(b=>!b.receiver);clearHoldPreview(fighter);if(receiver){scene.remove(receiver.obj);receiver.dispose();receiver=null;}entry=e;const url=new URL(location.href);url.searchParams.set('clip',e.id);history.replaceState(null,'',url);$('#user-review').textContent=animationReview(e);$('#loop').checked=!!e.loop&&STUDY_CONTEXT[e.key]?.motion!=='fall';appearanceStatus();$('#preview-help').textContent=e.kind==='procedural'?'Hold alignment preview: inspect both bodies and the hands. This is a held pose, not the reach, capture or throw sequence.':e.id.startsWith('study:')?'Editable candidate: watch the whole motion, then pause and step through it. This study is not assigned to gameplay.': 'Clip playback: watch the move, then pause and use Frame + to inspect contact. Selecting a character previews its appearance; it does not grant that character this move.';receiverLabel.hidden=e.kind!=='procedural';clip=resolveAnimationClip(e.id)||{duration:e.duration};time=0;center.y=STUDY_CONTEXT[e.key]?12:6;distance=STUDY_CONTEXT[e.key]?38:28;view(e.kind==='modular'?'side':'front');loadMarkers();if(e.kind==='procedural')makeReceiver();$('.eyebrow').textContent=e.kind==='procedural'?'NATIVE PAIRED HOLD / PROCEDURAL':STUDY_CONTEXT[e.key]?'AIRBORNE MOTION STUDY / PREVIEW ONLY':'AUTHORED CLIP PREVIEW';$('#clip-title').textContent=e.label;$('#metadata').replaceChildren();for(const [label,value] of [['Source take',e.take],['Duration',`${e.duration.toFixed(3)} seconds`],['Frames / keys',e.frames],...(e.markers?[['Release',e.markers.release.toFixed(3)+' seconds'],['Control returns',e.markers.controlReturn.toFixed(3)+' seconds'],['Hand',e.hand]]:[]),['Contact window',e.contact?`${e.contact.start.toFixed(3)}–${e.contact.end.toFixed(3)}s`:'Not a strike'],['Source',e.source?.author||'Unknown'],['Runtime',e.runtime],['Audio audit',e.audioStatus==='verified'?'Verified':e.audioStatus==='missing'?'Missing assignment':'Not audited — assignment and playback not verified']]){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;$('#metadata').append(dt,dd);}pause(true);const oldLink=$('#study-editor-link');oldLink?.remove();if(e.editorUrl){const link=document.createElement('a');link.id='study-editor-link';link.href=e.editorUrl;link.textContent='Edit this study';$('#metadata').after(link);}$('#validation').textContent=[e.issues.length?e.issues.join(', '):e.kind==='procedural'?'Held pose only: inspect hand and body alignment. This is not a grab-entry or throw animation.':'Pose data valid — inspect the moving model; gameplay acceptance is separate',...e.warnings].join(' · ');list();}
let savedDrafts={},draftReadError='';
try{savedDrafts=readMarkerDrafts(localStorage);}catch(e){draftReadError=e.message;}
function loadMarkers(){
 $('#marker-editor').hidden=entry.category!=='Melee';
 if(entry.category!=='Melee')return;
 clip=resolveAnimationClip(entry.id);
 let assigned=null,assignmentError='';
 try{assigned=loadProfile(select.value)?.model?.strikeMarkers?.[entry.key]??null;}catch(error){assignmentError=error.message;}
 const draft=savedDrafts[entry.id];if(draft||assigned)clip=clipWithMarkers(draft||assigned);
 $('#marker-start').value=String(clip.contactStart);$('#marker-end').value=String(clip.contactEnd);
 $('#marker-status').textContent=[draftReadError,assignmentError,draft?'Shared local draft preview. Assign to apply it to this character.':assigned?'Selected character’s assigned markers loaded.':'Source markers. This character has no assignment.'].filter(Boolean).join(' ');
 $('#marker-save').disabled=!!draftReadError;$('#marker-revert').disabled=!!draftReadError;
}
function editMarkers(){const a=$('#marker-start').value,b=$('#marker-end').value;if(!a||!b)throw Error('Enter both marker times.');const draft=markerDraft(entry.id,Number(a),Number(b));clip=clipWithMarkers(draft);return draft;}
function markerAction(fn){try{fn();}catch(e){$('#marker-status').textContent=e.message;}}
$('#marker-preview').onclick=()=>markerAction(()=>{editMarkers();pause(false);time=clip.contactStart;$('#marker-status').textContent='At draft contact start. Preview only.';});
$('#marker-save').onclick=()=>markerAction(()=>{savedDrafts=saveMarkerDraft(localStorage,editMarkers());$('#marker-status').textContent='Saved locally. Not assigned to gameplay.';});
$('#marker-revert').onclick=()=>markerAction(()=>{savedDrafts=revertMarkerDraft(localStorage,entry.id);clip=resolveAnimationClip(entry.id);loadMarkers();});
$('#marker-assign').onclick=()=>markerAction(()=>{const def=ROSTER.find(d=>d.id===select.value),profile=loadProfile(def.id)||profileFromDef(def),draft=editMarkers();profile.model.strikeMarkers={...profile.model.strikeMarkers,[entry.key]:draft};if((entry.key==='power'?profile.model.heavyStrikes:profile.model.strikes)==='procedural')throw Error('This character uses procedural strikes. Choose authored strikes in Character Studio first.');saveProfile(profile);$('#marker-status').textContent=def.name+' assigned. Applies when starting a new game. Other characters unchanged.';});
$('#marker-unassign').onclick=()=>markerAction(()=>{const def=ROSTER.find(d=>d.id===select.value),profile=loadProfile(def.id);if(profile?.model.strikeMarkers){delete profile.model.strikeMarkers[entry.key];saveProfile(profile);}loadMarkers();$('#marker-status').textContent=def.name+' assignment removed. Takes effect next game.';});
$('#marker-export').onclick=()=>markerAction(()=>{const draft=editMarkers(),url=URL.createObjectURL(new Blob([JSON.stringify(draft,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=entry.id.replace('/','-')+'-markers.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
attentionSelect.onchange=list;$('#search').oninput=list;$('#category').onchange=list;select.onchange=()=>{character();loadMarkers();};
function pause(value){playing=value;$('#play').textContent=playing?'Pause':'Play';}
$('#play').onclick=()=>{if(!playing&&time>=clip.duration)time=0;pause(!playing);};$('#restart').onclick=()=>{time=0;pause(true);};$('#step').onclick=()=>{pause(false);time=Math.min(clip.duration,time+1/(entry.source?.sampleRate||60));};$('#speed').onchange=e=>rate=Number(e.target.value);$('#scrub').oninput=e=>{pause(false);time=Number(e.target.value)*clip.duration;};
const phases=document.createElement('div');phases.className='transport';phases.setAttribute('aria-label','Review key moments');for(const p of [0,.25,.5,.75,1]){const b=document.createElement('button');b.textContent=Math.round(p*100)+'%';b.onclick=()=>{pause(false);time=p*clip.duration;};phases.append(b);}$('#preview-help').before(phases);
for(const b of document.querySelectorAll('[data-view]'))b.onclick=()=>view(b.dataset.view);
$('#export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({...catalog,entries:catalog.entries.map(e=>({...e,userReview:animationReview(e)}))},null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='powerworld-animation-catalog.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
new ResizeObserver(()=>{const host=$('#stage');renderer.setSize(host.clientWidth,host.clientHeight);camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();}).observe($('#stage'));
character();choose(entry);let last=performance.now();function render(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(playing){const next=advancePreview(time,dt*rate,clip.duration,$('#loop').checked);time=next.time;if(next.ended)pause(false);}for(const b of base){b.o.position.copy(b.p);b.o.quaternion.copy(b.q);b.o.scale.copy(b.s);}if(entry.kind==='modular'&&fullActor){fullActor.pose(entry.take,time/clip.duration);fullActor.actor.position.y=previewOffset(STUDY_CONTEXT[entry.key],time/clip.duration);fighter.obj.visible=false;}else if(entry.kind==='procedural'){poseHoldPair(fighter,receiver,time,entry.friendly,entry.holdMode);}else if(fighter.parts.rig){samplePoseFrame(clip,time/clip.duration,frame,false);applyAuthoredPose(fighter,frame,1,{legs:true,hips:true,support:true});updateLimbSurfaces(fighter.parts);updateHeroSkin(fighter.parts);const modular=fighter._modularCharacter;if(modular){const take=modular.clips.has(entry.take)?entry.take:entry.category==='Melee'?'Punch_Cross':'Idle_Loop';if(fullActor?.clips.has(entry.take)){if(!modular.clips.has(entry.take))modular.clips.set(entry.take,fullActor.clips.get(entry.take));modular.pose(entry.take,time/clip.duration);}else modular.poseFromNative({take,phase:time/clip.duration});}}$('#scrub').value=String(time/clip.duration);$('#clock').textContent=`${time.toFixed(2)} / ${clip.duration.toFixed(2)}s`;syncEquipment();if(poseFocusRoot){const delta=poseFocusRoot.position.clone().sub(focusLastPosition);camera.position.add(delta);controls.target.add(delta);center.add(delta);focusLastPosition.copy(poseFocusRoot.position);}controls.update();renderer.render(scene,camera);requestAnimationFrame(render);}requestAnimationFrame(render);
window.animationLibrary={get appearance(){return {hero:fighter.def.id,colors:{...fighter.def.colors},receiver:receiver?{hero:receiver.def.id,colors:{...receiver.def.colors}}:null};},get selected(){return entry.id;},get time(){return time;},get playing(){return playing;},get hasRig(){return !!fighter.parts.rig;}};

const fullButton=document.createElement('button');fullButton.id='load-full-motions';fullButton.textContent='Load full-rig clips and editable studies';$('#category').before(fullButton);
fullButton.onclick=async()=>{try{fullButton.disabled=true;fullButton.textContent='Loading mapped source clips…';const baseBank=await loadModularMotionBank();let paidBank={entries:[]};try{paidBank=await loadPaidMotionBank();}catch(error){console.warn('Purchased source preview unavailable:',error.message);}const bank={...baseBank,entries:[...baseBank.entries,...paidBank.entries]},asset=await modularAsset();const source={...asset,animations:[...asset.animations]};for(const e of bank.entries)if(!source.animations.some(c=>c.name===e.take))source.animations.push(T.AnimationClip.parse(e.clip));fullActor=createModularActor(source);fullActor.pose('Idle_Loop',0);const studies=characterStudyCatalog(fullActor.actor);for(const study of studies){fullActor.clips.set(study.clip.name,study.clip);catalog.entries.push({...study.entry,category:animationFamily(study.entry.label||study.entry.key)});}fullActor.actor.scale.setScalar((fighter.parts.head.position.y+.8*fighter.parts.head.scale.y)/1.8325);fullActor.actor.visible=false;applyModularRecipe(fullActor.meshes,MODULAR_RECIPES.vegas);scene.add(fullActor.actor);for(const e of bank.entries)catalog.entries.push({id:e.id,key:e.take,take:e.take,label:e.take,category:animationFamily(e.take),kind:'modular',duration:e.duration,loop:e.loop,frames:e.clip.tracks[0]?.times.length||0,contact:null,source:{...e.source,author:e.id.startsWith('paid/')?(e.source?.author||e.source?.pack||'Purchased source / retargeted candidate'):e.id.startsWith('derived/')?'Power World derivative / Quaternius source':'Quaternius'},runtime:'Shared modular rig · source motion preview',issues:[],warnings:[e.id.startsWith('paid/')?'Purchased source retarget: inspect orientation, grip and loop seam before assigning': 'Gameplay contact timing and assignments remain separate',...(e.warnings||[])],audioStatus:'unverified'});for(const family of new Set(catalog.entries.map(e=>e.category)))if(![...$('#category').options].some(o=>o.value===family))$('#category').add(new Option(family,family));fullButton.textContent=bank.entries.length+' source clips + '+studies.length+' studies loaded';list();choose(catalog.entries.find(e=>e.id===requestedClip)||entry);}catch(e){fullButton.textContent=e.message;fullButton.disabled=false;}};

// Make the shared source clips and editable actions discoverable without a hidden loading step.
fullButton.onclick();
