import {poseHoldPair,clearHoldPreview} from './paired-hold-preview.js';
import {mountFavorites} from './library-favorites.js';
import authoringGuide from '../../docs/gameplay/ANIMATION_CONTENT_WORKER_HANDOFF.md?raw';
import {applyProfile,loadProfile,saveProfile,profileFromDef} from './studio-profile.js';
import {markerDraft,clipWithMarkers,readMarkerDrafts,saveMarkerDraft,revertMarkerDraft} from './animation-drafts.js';
import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {Fighter} from '../engine/entity.js';
import {updateLimbSurfaces} from '../engine/hero-limb-surface.js';
import {updateHeroSkin} from '../engine/hero-skin.js';
import {ROSTER} from '../data/characters.js';
import {buildAnimationCatalog,resolveAnimationClip,animationAttention} from '../data/animation-catalog.js';
import {samplePoseFrame,applyAuthoredPose} from '../engine/authored-pose.js';
import '../styles/tokens.css';
import './animation-page.css';
const catalog=buildAnimationCatalog();catalog.entries=[...catalog.entries,...catalog.procedural];
document.body.innerHTML=`<header><div><p class="brand">POWERWORLD / CONTENT STUDIO</p><h1>Animation Library</h1></div><nav><a href="studio.html">Character Studio</a><a href="sound-library.html">Sound Library</a><a href="powerworld.html">Play</a></nav></header><main><aside class="catalog"><label for="search">Find an animation</label><input id="search" type="search" placeholder="Search name or source take"><label for="category">Move family</label><select id="category"><option value="">All families</option></select><p id="count" role="status"></p><div id="clips"></div></aside><section class="viewer"><div class="stagebar"><div><span class="eyebrow">AUTHORED CLIP PREVIEW</span><h2 id="clip-title"></h2></div><label>Character <select id="character"></select></label></div><div id="stage"><div class="camera" aria-label="Camera angles"><button data-view="front">Front</button><button data-view="side">Side</button><button data-view="back">Back</button><button data-view="overhead">Above</button></div><span class="stage-note">Drag to orbit · scroll to zoom</span></div><div class="transport"><button id="play">Pause</button><button id="step" title="Pause and advance one source frame">Frame +</button><button id="restart">Restart</button><label>Speed <select id="speed"><option value=".25">¼×</option><option value=".5">½×</option><option value="1" selected>1×</option></select></label><output id="clock"></output><input id="scrub" aria-label="Animation position" type="range" min="0" max="1" step=".001" value="0"></div><p class="disclosure">Pose preview only. Gameplay controls approach, hit detection, damage and recovery timing.</p></section><aside class="details"><h2>Clip details</h2><dl id="metadata"></dl><h3>Validation</h3><div id="validation"></div><section id="marker-editor"><h3>Contact markers</h3><p class="disclosure">Source clip time, in seconds. Saved drafts do not change live combat.</p><label>Start <input id="marker-start" type="number" min="0" step=".001"></label><label>End <input id="marker-end" type="number" min="0" step=".001"></label><button id="marker-preview">Preview contact</button><button id="marker-save">Save draft</button><button id="marker-revert">Revert to source</button><button id="marker-export">Export draft</button><button id="marker-assign">Assign to selected character</button><button id="marker-unassign">Remove character assignment</button><p id="marker-status" role="status"></p></section><button id="export">Export catalog</button><p class="disclosure">Assignments change source-pose timing for this strike. Paired holds use native procedural poses; their timing is reviewed in the Threat Room. Audio links and other procedural families remain to be integrated.</p></aside></main>`;
const $=s=>document.querySelector(s),select=$('#character');
const guideButton=document.createElement('button');guideButton.textContent='Download authoring guide';$('#export').after(guideButton);
guideButton.onclick=()=>{const url=URL.createObjectURL(new Blob([authoringGuide],{type:'text/markdown'})),a=document.createElement('a');a.href=url;a.download='powerworld-animation-authoring.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
for(const d of ROSTER)select.add(new Option(d.name,d.id));select.value='vega';
const receiverLabel=document.createElement('label');receiverLabel.textContent='Held character';const receiverSelect=document.createElement('select');receiverSelect.setAttribute('aria-label','Held character');for(const d of ROSTER)receiverSelect.add(new Option(d.name,d.id));receiverSelect.value='merc';receiverLabel.append(receiverSelect);receiverLabel.hidden=true;$('#marker-editor').before(receiverLabel);receiverSelect.onchange=()=>character();
for(const name of new Set(catalog.entries.map(e=>e.category)))$('#category').add(new Option(name,name));
const attentionLabel=document.createElement('label');attentionLabel.htmlFor='attention';attentionLabel.textContent='Authoring status';
const attentionSelect=document.createElement('select');attentionSelect.id='attention';
for(const [value,label]of [['','All statuses'],['any','Needs attention'],['invalid','Invalid / missing animation'],['motion','Motion needs review'],['audio-missing','Audio missing'],['audio-unverified','Audio not audited']])attentionSelect.add(new Option(label,value));
$('#category').after(attentionLabel,attentionSelect);
let entry=catalog.entries[0],clip=resolveAnimationClip(entry.id),time=0,playing=true,rate=1,fighter,receiver,base=[];
const scene=new T.Scene();scene.background=new T.Color('#171c20');
const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;
$('#stage').prepend(renderer.domElement);const camera=new T.PerspectiveCamera(38,1,.1,500),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=8;controls.maxDistance=100;
scene.add(new T.HemisphereLight('#edf4ff','#665342',1.4));const key=new T.DirectionalLight('#fff1d5',3);key.position.set(-15,25,18);scene.add(key);const rim=new T.DirectionalLight('#a6d6ef',1.3);rim.position.set(12,18,-15);scene.add(rim);
const floor=new T.Mesh(new T.CircleGeometry(100,64),new T.MeshStandardMaterial({color:'#252a2b',roughness:1}));floor.rotation.x=-Math.PI/2;floor.position.y=-.04;scene.add(floor);
const frame=new Float64Array(45);let center=new T.Vector3(),distance=30;
function view(name){const dirs={front:[0,.12,1],side:[1,.12,0],back:[0,.12,-1],overhead:[.01,1,.01]};camera.position.copy(center).add(new T.Vector3(...dirs[name]).normalize().multiplyScalar(distance));controls.target.copy(center);controls.update();}
const appearanceNotice=document.createElement('p');appearanceNotice.id='appearance-status';appearanceNotice.className='disclosure';appearanceNotice.setAttribute('role','status');$('.stagebar').after(appearanceNotice);
const appearanceSources=new Map();
function previewDefinition(id){const source=ROSTER.find(d=>d.id===id)||ROSTER[0];try{const profile=loadProfile(source.id);const def=profile?applyProfile(source,profile):source;appearanceSources.set(source.id,source.name+': '+(profile?'saved Studio appearance':'shipped appearance'));return def;}catch(error){appearanceSources.set(source.id,source.name+': saved profile could not load; showing shipped appearance. '+error.message);return source;}}
function appearanceStatus(){appearanceNotice.textContent=[appearanceSources.get(select.value),...(receiver?[appearanceSources.get(receiverSelect.value)]:[])].filter(Boolean).join(' · ');}
function makeReceiver(){receiver=new Fighter(previewDefinition(receiverSelect.value),{rimK:.14});scene.add(receiver.obj);poseHoldPair(fighter,receiver,0,entry.friendly);receiver.obj.traverse(o=>base.push({receiver:true,o,p:o.position.clone(),q:o.quaternion.clone(),s:o.scale.clone()}));center.z=1.65;distance=Math.max(distance,28);view('side');appearanceStatus();}
function character(){if(receiver){scene.remove(receiver.obj);receiver.dispose();receiver=null;}if(fighter){scene.remove(fighter.obj);fighter.dispose();}const def=previewDefinition(select.value);fighter=new Fighter(def,{rimK:.14});scene.add(fighter.obj);fighter.obj.updateMatrixWorld(true);base=[];fighter.obj.traverse(o=>base.push({o,p:o.position.clone(),q:o.quaternion.clone(),s:o.scale.clone()}));const box=new T.Box3().setFromObject(fighter.obj);box.getCenter(center);center.y=Math.max(4,center.y);distance=Math.max(18,box.getSize(new T.Vector3()).y*1.9);view('front');if(entry.kind==='procedural')makeReceiver();appearanceStatus();}
const favoritesHost=document.createElement('div');$('#category').after(favoritesHost);
const favorites=mountFavorites({host:favoritesHost,kind:'animations',selected:()=>entry.id,onChange:()=>list()});
function list(){favorites.sync();const q=$('#search').value.toLowerCase(),category=$('#category').value,entries=catalog.entries.filter(e=>favorites.matches(e.id)&&(!attentionSelect.value||animationAttention(e).some(b=>attentionSelect.value==='any'||b.kind===attentionSelect.value))&&(!category||e.category===category)&&`${e.label} ${e.take}`.toLowerCase().includes(q));$('#clips').replaceChildren();$('#count').textContent=`${entries.length} of ${catalog.entries.length} clips`;for(const e of entries){const b=document.createElement('button');b.className='clip';b.setAttribute('aria-pressed',String(e.id===entry.id));const strong=document.createElement('strong'),small=document.createElement('small');strong.textContent=e.label;small.textContent=`${e.category} · ${e.duration.toFixed(2)}s`;b.append(strong,small);for(const badge of animationAttention(e)){const tag=document.createElement('span');tag.className='authoring-badge';tag.dataset.kind=badge.kind;tag.textContent=badge.label;b.append(tag);}b.onclick=()=>choose(e);$('#clips').append(b);}if(!entries.length)$('#clips').textContent='No matching animations. Try another search.';}
function choose(e){base=base.filter(b=>!b.receiver);clearHoldPreview(fighter);if(receiver){scene.remove(receiver.obj);receiver.dispose();receiver=null;}entry=e;appearanceStatus();receiverLabel.hidden=e.kind!=='procedural';clip=resolveAnimationClip(e.id)||{duration:e.duration};time=0;loadMarkers();if(e.kind==='procedural')makeReceiver();$('.eyebrow').textContent=e.kind==='procedural'?'NATIVE PAIRED HOLD / PROCEDURAL':'AUTHORED CLIP PREVIEW';$('#clip-title').textContent=e.label;$('#metadata').replaceChildren();for(const [label,value] of [['Source take',e.take],['Duration',`${e.duration.toFixed(3)} seconds`],['Frames',e.frames],['Contact window',e.contact?`${e.contact.start.toFixed(3)}–${e.contact.end.toFixed(3)}s`:'Not a strike'],['Source',e.source?.author||'Unknown'],['Runtime',e.runtime],['Audio audit',e.audioStatus==='verified'?'Verified':e.audioStatus==='missing'?'Missing assignment':'Not audited — assignment and playback not verified']]){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;$('#metadata').append(dt,dd);}$('#validation').textContent=[e.issues.length?e.issues.join(', '):e.kind==='procedural'?'Native hold preview; no imported frames':'Pose data valid',...e.warnings].join(' · ');list();}
let savedDrafts={},draftReadError='';
try{savedDrafts=readMarkerDrafts(localStorage);}catch(e){draftReadError=e.message;}
function loadMarkers(){
 $('#marker-editor').hidden=entry.category!=='Melee';
 if(entry.category!=='Melee')return;
 const draft=savedDrafts[entry.id];if(draft)clip=clipWithMarkers(draft);
 $('#marker-start').value=String(clip.contactStart);$('#marker-end').value=String(clip.contactEnd);
 $('#marker-status').textContent=draftReadError||(draft?'Saved local draft loaded.':'Source markers. No draft saved.');
 $('#marker-save').disabled=!!draftReadError;$('#marker-revert').disabled=!!draftReadError;
}
function editMarkers(){const a=$('#marker-start').value,b=$('#marker-end').value;if(!a||!b)throw Error('Enter both marker times.');const draft=markerDraft(entry.id,Number(a),Number(b));clip=clipWithMarkers(draft);return draft;}
function markerAction(fn){try{fn();}catch(e){$('#marker-status').textContent=e.message;}}
$('#marker-preview').onclick=()=>markerAction(()=>{editMarkers();pause(false);time=clip.contactStart;$('#marker-status').textContent='At draft contact start. Preview only.';});
$('#marker-save').onclick=()=>markerAction(()=>{savedDrafts=saveMarkerDraft(localStorage,editMarkers());$('#marker-status').textContent='Saved locally. Not assigned to gameplay.';});
$('#marker-revert').onclick=()=>markerAction(()=>{savedDrafts=revertMarkerDraft(localStorage,entry.id);clip=resolveAnimationClip(entry.id);loadMarkers();});
$('#marker-assign').onclick=()=>markerAction(()=>{const def=ROSTER.find(d=>d.id===select.value),profile=loadProfile(def.id)||profileFromDef(def),draft=editMarkers();profile.model.strikeMarkers={...profile.model.strikeMarkers,[entry.key]:draft};if((entry.key==='power'?profile.model.heavyStrikes:profile.model.strikes)==='procedural')throw Error('This character uses procedural strikes. Choose authored strikes in Character Studio first.');saveProfile(profile);$('#marker-status').textContent=def.name+' assigned. Applies when starting a new game. Other characters unchanged.';});
$('#marker-unassign').onclick=()=>markerAction(()=>{const def=ROSTER.find(d=>d.id===select.value),profile=loadProfile(def.id);if(profile?.model.strikeMarkers){delete profile.model.strikeMarkers[entry.key];saveProfile(profile);}$('#marker-status').textContent=def.name+' assignment removed. Takes effect next game.';});
$('#marker-export').onclick=()=>markerAction(()=>{const draft=editMarkers(),url=URL.createObjectURL(new Blob([JSON.stringify(draft,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=entry.id.replace('/','-')+'-markers.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
attentionSelect.onchange=list;$('#search').oninput=list;$('#category').onchange=list;select.onchange=character;
function pause(value){playing=value;$('#play').textContent=playing?'Pause':'Play';}
$('#play').onclick=()=>pause(!playing);$('#restart').onclick=()=>{time=0;};$('#step').onclick=()=>{pause(false);time=Math.min(clip.duration,time+1/(entry.source?.sampleRate||60));};$('#speed').onchange=e=>rate=Number(e.target.value);$('#scrub').oninput=e=>{pause(false);time=Number(e.target.value)*clip.duration;};
for(const b of document.querySelectorAll('[data-view]'))b.onclick=()=>view(b.dataset.view);
$('#export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(catalog,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='powerworld-animation-catalog.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
new ResizeObserver(()=>{const host=$('#stage');renderer.setSize(host.clientWidth,host.clientHeight);camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();}).observe($('#stage'));
character();choose(entry);let last=performance.now();function render(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(playing)time=(time+dt*rate)%clip.duration;for(const b of base){b.o.position.copy(b.p);b.o.quaternion.copy(b.q);b.o.scale.copy(b.s);}if(entry.kind==='procedural'){poseHoldPair(fighter,receiver,time,entry.friendly);}else if(fighter.parts.rig){samplePoseFrame(clip,time/clip.duration,frame,false);applyAuthoredPose(fighter,frame,1,{legs:true,hips:true,support:true});updateLimbSurfaces(fighter.parts);updateHeroSkin(fighter.parts);}$('#scrub').value=String(time/clip.duration);$('#clock').textContent=`${time.toFixed(2)} / ${clip.duration.toFixed(2)}s`;controls.update();renderer.render(scene,camera);requestAnimationFrame(render);}requestAnimationFrame(render);
window.animationLibrary={get appearance(){return {hero:fighter.def.id,colors:{...fighter.def.colors},receiver:receiver?{hero:receiver.def.id,colors:{...receiver.def.colors}}:null};},get selected(){return entry.id;},get time(){return time;},get playing(){return playing;},get hasRig(){return !!fighter.parts.rig;}};
