import {gadgetCatalog} from '../data/gadget-catalog.js';

import './workshop-page.css';
const esc=s=>String(s??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rows=gadgetCatalog().map(({def,owners})=>({...def,owners}));

document.body.innerHTML='<nav class="workshop-nav"><a href="powerworld.html">POWERWORLD</a><a href="studio.html">Character Studio</a><a href="sound-library.html">Sound Library</a><a href="gadget-library.html" aria-current="page">Gadget Catalog</a></nav><main class="catalog-main"><h1>Gadget catalog</h1><p>Live definitions from character loadouts and Threat Lab issue. Search, compare and export a spreadsheet.</p><p>Read-only source view. Inventory equips and uses gadgets; this catalog does not change balance values.</p><div class="catalog-tools"><input aria-label="Search gadgets" placeholder="Search gadget, kind or character"><button id="export">Export CSV</button></div><p id="count" role="status"></p><div class="catalog-table"><table><thead><tr><th>Gadget / ID</th><th>Kind</th><th>Charges</th><th>Cooldown (s)</th><th>Configured effects</th><th>Issued to / carried by</th></tr></thead><tbody></tbody></table></div></main>';
function effects(d){return Object.entries(d).filter(([k])=>!['id','name','kind','charges','cd','owners'].includes(k)).map(([k,v])=>k+': '+JSON.stringify(v)).join(' · ')||'—';}
function filtered(){const q=document.querySelector('input').value.toLowerCase();return rows.filter(d=>JSON.stringify(d).toLowerCase().includes(q));}
function render(){const list=filtered();document.querySelector('#count').textContent=list.length+' gadget definitions';document.querySelector('tbody').innerHTML=list.map(d=>'<tr><td>'+esc(d.name||d.kind)+'<small>'+esc(d.id||'Character loadout')+'</small></td><td>'+esc(d.kind)+'</td><td>'+esc(d.charges??'Runtime default')+'</td><td>'+esc(d.cd??'Runtime default')+'</td><td>'+esc(effects(d))+'</td><td>'+esc(d.owners.join(', '))+'</td></tr>').join('');}
document.querySelector('input').oninput=render;document.querySelector('#export').onclick=()=>{const quote=x=>'"'+String(x??'').replaceAll('"','""')+'"';const lines=[['Name','ID','Kind','Charges','Cooldown seconds','Effects','Owners'],...filtered().map(d=>[d.name||d.kind,d.id,d.kind,d.charges,d.cd,effects(d),d.owners.join('; ')])];const blob=new Blob(['\ufeff'+lines.map(row=>row.map(quote).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='powerworld-gadgets.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};render();
