const DB_VERSION=1,DEFAULT_BUDGET=250*1024*1024,MAX_FRAMES=360,MAX_CLIP_BYTES=24*1024*1024;
const BACKUP_VERSION=1,MAX_BACKUP_BYTES=Math.ceil(MAX_CLIP_BYTES*4/3)+1024*1024;
const MEDIA_TYPES=new Set(['image/webp','image/jpeg','image/png']);
const req=r=>new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error||Error('IndexedDB request failed'));});
const done=tx=>new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onabort=tx.onerror=()=>reject(tx.error||Error('IndexedDB transaction failed'));});
const text=(v,n='value')=>{if(typeof v!=='string')throw TypeError(`${n} must be text`);return v;};
const title=v=>text(v??'','title').slice(0,120);
const safeInt=(v,n,min=0)=>{if(!Number.isSafeInteger(v)||v<min)throw TypeError(`${n} must be an integer >= ${min}`);return v;};
function metadata(clip,bytes){
 const heroIds=Array.isArray(clip.heroIds)?[...new Set(clip.heroIds.map(v=>text(v,'hero id')).filter(Boolean))]:[];
 return {id:text(clip.id,'id'),matchId:text(clip.matchId,'matchId'),createdAt:safeInt(clip.createdAt,'createdAt'),title:title(clip.title),tag:text(clip.tag,'tag'),heroIds,
  favorite:!!clip.favorite,fps:Number(clip.fps)||12,priority:Number(clip.priority)||0,width:safeInt(clip.width,'width',1),height:safeInt(clip.height,'height',1),
  slow:!!clip.slow,slowFrom:safeInt(clip.slowFrom??0,'slowFrom'),slowTo:safeInt(clip.slowTo??0,'slowTo'),audio:false,shots:Array.isArray(clip.shots)?structuredClone(clip.shots):[],t0:Number(clip.t0)||0,tLabel:typeof clip.tLabel==='string'?clip.tLabel:'',shotBy:typeof clip.shotBy==='string'?clip.shotBy:'',bytes};
}
async function validateFrames(frames,{dimensions}={}){
 if(!Array.isArray(frames)||!frames.length||frames.length>MAX_FRAMES)throw RangeError(`frames must contain 1-${MAX_FRAMES} images`);
 let bytes=0;for(let i=0;i<frames.length;i++){const b=frames[i];if(!(b instanceof Blob)||!MEDIA_TYPES.has(b.type))throw TypeError(`frame ${i} must be a WebP, JPEG, or PNG Blob`);bytes+=b.size;if(bytes>MAX_CLIP_BYTES)throw RangeError(`clip exceeds ${MAX_CLIP_BYTES} byte media limit`);}
 if(dimensions&&typeof createImageBitmap==='function')for(let i=0;i<frames.length;i++){let bitmap;try{bitmap=await createImageBitmap(frames[i]);if(bitmap.width!==dimensions.width||bitmap.height!==dimensions.height)throw RangeError(`frame ${i} dimensions do not match metadata`);}catch(e){if(e instanceof RangeError)throw e;throw TypeError(`frame ${i} is not a decodable image`);}finally{bitmap?.close();}}
 return bytes;
}
export function createNewsArchive({indexedDB=globalThis.indexedDB,dbName='powerworld-news-v1'}={}){
 if(!indexedDB)throw Error('IndexedDB is unavailable');let dbPromise=null,closed=false;
 const open=()=>{if(closed)throw Error('News archive is closed');if(!dbPromise)dbPromise=new Promise((resolve,reject)=>{const r=indexedDB.open(dbName,DB_VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains('metadata')){const s=db.createObjectStore('metadata',{keyPath:'id'});s.createIndex('createdAt','createdAt');s.createIndex('heroIds','heroIds',{multiEntry:true});s.createIndex('tag','tag');s.createIndex('favorite','favorite');}if(!db.objectStoreNames.contains('media'))db.createObjectStore('media',{keyPath:'id'});if(!db.objectStoreNames.contains('settings'))db.createObjectStore('settings',{keyPath:'key'});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>{dbPromise=null;reject(r.error||Error('Unable to open news archive'));};r.onblocked=()=>{dbPromise=null;reject(Error('News archive open blocked'));};});return dbPromise;};
 async function budget(store){return (await req(store.get('budget')))?.value??DEFAULT_BUDGET;}
 async function list({heroId='',favoritesOnly=false,event='',limit=100,offset=0}={}){limit=Math.max(0,Math.min(1000,safeInt(limit,'limit')));offset=safeInt(offset,'offset');const db=await open(),tx=db.transaction('metadata','readonly'),s=tx.objectStore('metadata'),rows=[];await new Promise((resolve,reject)=>{const r=s.index('createdAt').openCursor(null,'prev');r.onerror=()=>reject(r.error);r.onsuccess=()=>{const c=r.result;if(!c)return resolve();const m=c.value,match=(!heroId||m.heroIds.includes(heroId))&&(!favoritesOnly||m.favorite)&&(!event||m.tag===event);if(match&&offset)offset--;else if(match&&rows.length<limit)rows.push(m);if(rows.length>=limit)return resolve();c.continue();};});await done(tx);return rows;}
 async function get(id){const db=await open(),tx=db.transaction(['metadata','media'],'readonly'),m=await req(tx.objectStore('metadata').get(id)),media=m&&await req(tx.objectStore('media').get(id));await done(tx);return m&&media?{...m,frames:media.frames}:null;}
 async function put(clip){const bytes=await validateFrames(clip.frames,{dimensions:clip}),m=metadata(clip,bytes),db=await open(),tx=db.transaction(['metadata','media','settings'],'readwrite'),ms=tx.objectStore('metadata'),med=tx.objectStore('media'),set=tx.objectStore('settings');try{const max=await budget(set),old=await req(ms.get(m.id));if(old?.favorite)m.favorite=true;let all=await req(ms.getAll()),used=all.reduce((n,x)=>n+x.bytes,0)-(old?.bytes||0);const victims=all.filter(x=>x.id!==m.id&&!x.favorite).sort((a,b)=>a.createdAt-b.createdAt);while(used+bytes>max&&victims.length){const v=victims.shift();used-=v.bytes;ms.delete(v.id);med.delete(v.id);}if(used+bytes>max)throw RangeError('News archive budget is filled by favorites');ms.put(m);med.put({id:m.id,frames:[...clip.frames]});await done(tx);return m;}catch(e){try{tx.abort();}catch{}throw e;}}
 async function update(id,patch={}){const db=await open(),tx=db.transaction(['metadata','media','settings'],'readwrite'),s=tx.objectStore('metadata');try{const m=await req(s.get(id));if(!m)throw Error(`Archived clip not found: ${id}`);if('title'in patch)m.title=title(patch.title);if('favorite'in patch)m.favorite=!!patch.favorite;s.put(m);await done(tx);return m;}catch(e){try{tx.abort();}catch{}throw e;}}
 async function remove(id){const db=await open(),tx=db.transaction(['metadata','media'],'readwrite');tx.objectStore('metadata').delete(id);tx.objectStore('media').delete(id);await done(tx);}
 async function stats(){const db=await open(),tx=db.transaction(['metadata','settings'],'readonly'),all=await req(tx.objectStore('metadata').getAll()),budgetBytes=await budget(tx.objectStore('settings'));await done(tx);return {bytes:all.reduce((n,x)=>n+x.bytes,0),count:all.length,favorites:all.filter(x=>x.favorite).length,budgetBytes};}
 async function setBudget(bytes){safeInt(bytes,'budget',1);const db=await open(),tx=db.transaction(['metadata','media','settings'],'readwrite'),ms=tx.objectStore('metadata'),med=tx.objectStore('media'),set=tx.objectStore('settings');const all=await req(ms.getAll());let used=all.reduce((n,x)=>n+x.bytes,0);for(const v of all.filter(x=>!x.favorite).sort((a,b)=>a.createdAt-b.createdAt)){if(used<=bytes)break;used-=v.bytes;ms.delete(v.id);med.delete(v.id);}set.put({key:'budget',value:bytes});await done(tx);return bytes;}
 async function exportClip(id){const clip=await get(id);if(!clip)throw Error(`Archived clip not found: ${id}`);const frames=[];for(const b of clip.frames)frames.push({type:b.type,data:await blobToBase64(b)});return new Blob([JSON.stringify({kind:'powerworld-news-clip',version:BACKUP_VERSION,clip:{...clip,frames}})],{type:'application/json'});}
 async function importBackup(blob){if(!(blob instanceof Blob)||blob.size>MAX_BACKUP_BYTES)throw RangeError('Backup file is too large');let data;try{data=JSON.parse(await blob.text());}catch{throw TypeError('Backup is not valid JSON');}if(data?.kind!=='powerworld-news-clip'||data.version!==BACKUP_VERSION)throw TypeError('Unsupported backup version');if(!Array.isArray(data.clip?.frames)||data.clip.frames.length>MAX_FRAMES)throw RangeError('Invalid backup frame count');let encoded=0;for(const f of data.clip.frames){if(typeof f?.data!=='string'||!MEDIA_TYPES.has(f.type))throw TypeError('Invalid backup frame content');encoded+=f.data.length;if(encoded>Math.ceil(MAX_CLIP_BYTES*4/3)+8)throw RangeError('Encoded backup media exceeds limit');}const frames=data.clip.frames.map(f=>new Blob([base64Bytes(f.data)],{type:f.type}));return put({...data.clip,frames});}
 function close(){closed=true;dbPromise?.then(db=>db.close()).catch(()=>{});dbPromise=null;}
 return {list,get,put,update,remove,stats,setBudget,exportClip,importBackup,close};
}
function blobToBase64(blob){return blob.arrayBuffer().then(buffer=>{let s='',a=new Uint8Array(buffer);for(let i=0;i<a.length;i+=0x8000)s+=String.fromCharCode(...a.subarray(i,i+0x8000));return btoa(s);});}
function base64Bytes(value){let s;try{s=atob(value);}catch{throw TypeError('Invalid base64 frame data');}const a=new Uint8Array(s.length);for(let i=0;i<s.length;i++)a[i]=s.charCodeAt(i);return a;}
