const DB_VERSION=1,DEFAULT_BUDGET=250*1024*1024,MAX_FRAMES=360,MAX_CLIP_BYTES=24*1024*1024;
const BACKUP_VERSION=1,MAX_BACKUP_BYTES=Math.ceil(MAX_CLIP_BYTES*4/3)+1024*1024;
const MEDIA_TYPES=new Set(['image/webp','image/jpeg','image/png']);
const MAX_DIMENSION=2048,MAX_PIXELS=4_000_000;
const req=r=>new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error||Error('IndexedDB request failed'));});
const done=tx=>new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onabort=tx.onerror=()=>reject(tx.error||Error('IndexedDB transaction failed'));});
const text=(v,n='value')=>{if(typeof v!=='string')throw TypeError(`${n} must be text`);return v;};
const title=v=>text(v??'','title').slice(0,120);
const safeInt=(v,n,min=0)=>{if(!Number.isSafeInteger(v)||v<min)throw TypeError(`${n} must be an integer >= ${min}`);return v;};
const boundedText=(v,n,max)=>{v=text(v,n);if(!v||v.length>max)throw RangeError(`${n} must contain 1-${max} characters`);return v;};
const finite=(v,n,min,max)=>{v=Number(v);if(!Number.isFinite(v)||v<min||v>max)throw RangeError(`${n} must be between ${min} and ${max}`);return v;};
function metadata(clip,bytes){
 if(!Array.isArray(clip.heroIds)||clip.heroIds.length>16)throw RangeError('heroIds must contain at most 16 entries');
 const heroIds=[...new Set(clip.heroIds.map(v=>boundedText(v,'hero id',64)))];
 const shots=Array.isArray(clip.shots)?structuredClone(clip.shots):[];if(shots.length>64||JSON.stringify(shots).length>65536)throw RangeError('shots metadata exceeds limit');
 return {id:boundedText(clip.id,'id',128),matchId:boundedText(clip.matchId,'matchId',128),createdAt:safeInt(clip.createdAt,'createdAt'),title:title(clip.title),tag:boundedText(clip.tag,'tag',40),heroIds,
  favorite:!!clip.favorite,fps:finite(clip.fps,'fps',1,60),priority:finite(clip.priority??0,'priority',0,10),width:safeInt(clip.width,'width',1),height:safeInt(clip.height,'height',1),
  slow:!!clip.slow,slowFrom:safeInt(clip.slowFrom??0,'slowFrom'),slowTo:safeInt(clip.slowTo??0,'slowTo'),audio:false,shots,t0:finite(clip.t0??0,'t0',0,1e9),tLabel:typeof clip.tLabel==='string'?clip.tLabel.slice(0,32):'',shotBy:typeof clip.shotBy==='string'?clip.shotBy.slice(0,120):'',bytes};
}
function imageDimensions(bytes,type){
 const b=new Uint8Array(bytes),v=new DataView(bytes);let width=0,height=0;
 if(type==='image/png'){if(b.length<24||![137,80,78,71,13,10,26,10].every((x,i)=>b[i]===x)||String.fromCharCode(...b.slice(12,16))!=='IHDR')throw TypeError('Invalid PNG header');width=v.getUint32(16);height=v.getUint32(20);}
 else if(type==='image/jpeg'){if(b.length<4||b[0]!==255||b[1]!==216)throw TypeError('Invalid JPEG header');for(let i=2;i+8<b.length;){if(b[i++]!==255)continue;const marker=b[i++],len=(b[i]<<8)|b[i+1];if([0xc0,0xc1,0xc2,0xc3,0xc5,0xc6,0xc7,0xc9,0xca,0xcb,0xcd,0xce,0xcf].includes(marker)){height=(b[i+3]<<8)|b[i+4];width=(b[i+5]<<8)|b[i+6];break;}if(len<2)break;i+=len;}}
 else {if(b.length<30||String.fromCharCode(...b.slice(0,4))!=='RIFF'||String.fromCharCode(...b.slice(8,12))!=='WEBP')throw TypeError('Invalid WebP header');const kind=String.fromCharCode(...b.slice(12,16));if(kind==='VP8X'){width=1+b[24]+(b[25]<<8)+(b[26]<<16);height=1+b[27]+(b[28]<<8)+(b[29]<<16);}else if(kind==='VP8L'&&b[20]===47){width=1+b[21]+((b[22]&63)<<8);height=1+(b[22]>>6)+(b[23]<<2)+((b[24]&15)<<10);}else if(kind==='VP8 '&&b.length>=30&&b[23]===157&&b[24]===1&&b[25]===42){width=(b[26]|b[27]<<8)&0x3fff;height=(b[28]|b[29]<<8)&0x3fff;}}
 if(!width||!height)throw TypeError(`Invalid ${type.slice(6).toUpperCase()} header`);if(width>MAX_DIMENSION||height>MAX_DIMENSION||width*height>MAX_PIXELS)throw RangeError('Image dimensions exceed pixel limit');return {width,height};
}
async function validateFrames(frames,{dimensions}={}){
 if(!Array.isArray(frames)||!frames.length||frames.length>MAX_FRAMES)throw RangeError(`frames must contain 1-${MAX_FRAMES} images`);
 let bytes=0;for(let i=0;i<frames.length;i++){const b=frames[i];if(!(b instanceof Blob)||!MEDIA_TYPES.has(b.type))throw TypeError(`frame ${i} must be a WebP, JPEG, or PNG Blob`);bytes+=b.size;if(bytes>MAX_CLIP_BYTES)throw RangeError(`clip exceeds ${MAX_CLIP_BYTES} byte media limit`);const d=imageDimensions(await b.arrayBuffer(),b.type);if(dimensions&&(d.width!==dimensions.width||d.height!==dimensions.height))throw RangeError(`frame ${i} dimensions do not match metadata`);}
 if(dimensions&&typeof createImageBitmap==='function')for(let i=0;i<frames.length;i++){let bitmap;try{bitmap=await createImageBitmap(frames[i]);if(bitmap.width!==dimensions.width||bitmap.height!==dimensions.height)throw RangeError(`frame ${i} dimensions do not match metadata`);}catch(e){if(e instanceof RangeError)throw e;throw TypeError(`frame ${i} is not a decodable image`);}finally{bitmap?.close();}}
 return bytes;
}
export function createNewsArchive({indexedDB=globalThis.indexedDB,dbName='powerworld-news-v1'}={}){
 if(!indexedDB)throw Error('IndexedDB is unavailable');let dbPromise=null,closed=false;
 const open=()=>{if(closed)throw Error('News archive is closed');if(!dbPromise)dbPromise=new Promise((resolve,reject)=>{let failed=false;const r=indexedDB.open(dbName,DB_VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains('metadata')){const s=db.createObjectStore('metadata',{keyPath:'id'});s.createIndex('createdAt','createdAt');s.createIndex('heroIds','heroIds',{multiEntry:true});s.createIndex('tag','tag');s.createIndex('favorite','favorite');}if(!db.objectStoreNames.contains('media'))db.createObjectStore('media',{keyPath:'id'});if(!db.objectStoreNames.contains('settings'))db.createObjectStore('settings',{keyPath:'key'});};r.onsuccess=()=>{if(failed)r.result.close();else resolve(r.result);};r.onerror=()=>{failed=true;dbPromise=null;reject(r.error||Error('Unable to open news archive'));};r.onblocked=()=>{failed=true;dbPromise=null;reject(Error('News archive open blocked'));};});return dbPromise;};
 async function budget(store){return (await req(store.get('budget')))?.value??DEFAULT_BUDGET;}
 async function list({heroId='',favoritesOnly=false,event='',limit=100,offset=0}={}){limit=Math.max(0,Math.min(1000,safeInt(limit,'limit')));offset=safeInt(offset,'offset');const db=await open(),tx=db.transaction('metadata','readonly'),s=tx.objectStore('metadata'),rows=[];await new Promise((resolve,reject)=>{const r=s.index('createdAt').openCursor(null,'prev');r.onerror=()=>reject(r.error);r.onsuccess=()=>{const c=r.result;if(!c)return resolve();const m=c.value,match=(!heroId||m.heroIds.includes(heroId))&&(!favoritesOnly||m.favorite)&&(!event||m.tag===event);if(match&&offset)offset--;else if(match&&rows.length<limit)rows.push(m);if(rows.length>=limit)return resolve();c.continue();};});await done(tx);return rows;}
 async function get(id){const db=await open(),tx=db.transaction(['metadata','media'],'readonly'),m=await req(tx.objectStore('metadata').get(id)),media=m&&await req(tx.objectStore('media').get(id));await done(tx);return m&&media?{...m,frames:media.frames}:null;}
 async function put(clip){const bytes=await validateFrames(clip.frames,{dimensions:clip}),m=metadata(clip,bytes),db=await open(),tx=db.transaction(['metadata','media','settings'],'readwrite'),ms=tx.objectStore('metadata'),med=tx.objectStore('media'),set=tx.objectStore('settings');try{const max=await budget(set),old=await req(ms.get(m.id));if(old){m.favorite=old.favorite;m.title=old.title;}let all=await req(ms.getAll()),used=all.reduce((n,x)=>n+x.bytes,0)-(old?.bytes||0);const victims=all.filter(x=>x.id!==m.id&&!x.favorite).sort((a,b)=>a.createdAt-b.createdAt);while(used+bytes>max&&victims.length){const v=victims.shift();used-=v.bytes;ms.delete(v.id);med.delete(v.id);}if(used+bytes>max)throw RangeError('News archive budget is filled by favorites');ms.put(m);med.put({id:m.id,frames:[...clip.frames]});await done(tx);return m;}catch(e){try{tx.abort();}catch{}throw e;}}
 async function update(id,patch={}){const db=await open(),tx=db.transaction(['metadata','media','settings'],'readwrite'),s=tx.objectStore('metadata');try{const m=await req(s.get(id));if(!m)throw Error(`Archived clip not found: ${id}`);if('title'in patch)m.title=title(patch.title);if('favorite'in patch)m.favorite=!!patch.favorite;s.put(m);await done(tx);return m;}catch(e){try{tx.abort();}catch{}throw e;}}
 async function remove(id){const db=await open(),tx=db.transaction(['metadata','media'],'readwrite');tx.objectStore('metadata').delete(id);tx.objectStore('media').delete(id);await done(tx);}
 async function stats(){const db=await open(),tx=db.transaction(['metadata','settings'],'readonly'),all=await req(tx.objectStore('metadata').getAll()),budgetBytes=await budget(tx.objectStore('settings'));await done(tx);return {bytes:all.reduce((n,x)=>n+x.bytes,0),count:all.length,favorites:all.filter(x=>x.favorite).length,budgetBytes};}
 async function setBudget(bytes){safeInt(bytes,'budget',1);const db=await open(),tx=db.transaction(['metadata','media','settings'],'readwrite'),ms=tx.objectStore('metadata'),med=tx.objectStore('media'),set=tx.objectStore('settings');const all=await req(ms.getAll());let used=all.reduce((n,x)=>n+x.bytes,0);for(const v of all.filter(x=>!x.favorite).sort((a,b)=>a.createdAt-b.createdAt)){if(used<=bytes)break;used-=v.bytes;ms.delete(v.id);med.delete(v.id);}set.put({key:'budget',value:bytes});await done(tx);return bytes;}
 async function exportClip(id){const clip=await get(id);if(!clip)throw Error(`Archived clip not found: ${id}`);const frames=[];for(const b of clip.frames)frames.push({type:b.type,data:await blobToBase64(b)});return new Blob([JSON.stringify({kind:'powerworld-news-clip',version:BACKUP_VERSION,clip:{...clip,frames}})],{type:'application/json'});}
 async function importBackup(blob){if(!(blob instanceof Blob)||blob.size>MAX_BACKUP_BYTES)throw RangeError('Backup file is too large');let data;try{data=JSON.parse(await blob.text());}catch{throw TypeError('Backup is not valid JSON');}if(data?.kind!=='powerworld-news-clip'||data.version!==BACKUP_VERSION)throw TypeError('Unsupported backup version');if(!Array.isArray(data.clip?.frames)||data.clip.frames.length>MAX_FRAMES)throw RangeError('Invalid backup frame count');let encoded=0;for(const f of data.clip.frames){if(typeof f?.data!=='string'||!MEDIA_TYPES.has(f.type))throw TypeError('Invalid backup frame content');encoded+=f.data.length;if(encoded>Math.ceil(MAX_CLIP_BYTES*4/3)+8)throw RangeError('Encoded backup media exceeds limit');}const frames=data.clip.frames.map(f=>new Blob([base64Bytes(f.data)],{type:f.type}));return put({...data.clip,frames});}
 function close(){closed=true;dbPromise?.then(db=>db.close()).catch(()=>{});dbPromise=null;}
 return {list,get,put,update,remove,stats,setBudget,exportClip,importBackup,close};
}
function blobToBase64(blob){return blob.arrayBuffer().then(buffer=>{let s='',a=new Uint8Array(buffer);for(let i=0;i<a.length;i+=0x8000)s+=String.fromCharCode(...a.subarray(i,i+0x8000));return btoa(s);});}
function base64Bytes(value){let s;try{s=atob(value);}catch{throw TypeError('Invalid base64 frame data');}const a=new Uint8Array(s.length);for(let i=0;i<s.length;i++)a[i]=s.charCodeAt(i);return a;}
