import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {SoundLibrary} from '../src/core/sound-library.js';
const pack=JSON.parse(await readFile('public/audio/ai-pass/library.json','utf8'));
const fixture=()=>new SoundLibrary({storage:null,context:{decodeAudioData:async()=>({duration:1})}});
test('AI pack adds missing recordings and preserves twelve bundled defaults and repeating does not replace existing choices',async()=>{const l=fixture();assert.deepEqual(await l.addMissingRecordings(pack),{added:25,kept:12});const state=l.state;assert.deepEqual(await l.addMissingRecordings(pack),{added:0,kept:37});assert.equal(l.state,state);});
test('existing recordings, gain, and inactive settings survive the additive import',async()=>{const l=fixture();await l.importPackage({...pack,bindings:{light:{...pack.bindings.light,name:'my-punch.wav'}},settings:{light:{source:'chosen',gain:.1},heavy:{source:'placeholder',gain:.2}}});await l.addMissingRecordings(pack);assert.equal(l.state.bindings.light.name,'my-punch.wav');assert.equal(l.state.settings.light.gain,.1);assert.equal(l.state.settings.heavy.source,'placeholder');assert.equal(l.state.settings.heavy.gain,.2);});
test('failed media decode leaves the full previous library unchanged',async()=>{const l=fixture(),state=l.state;l.ctx.decodeAudioData=async()=>{throw Error('bad media')};await assert.rejects(l.addMissingRecordings(pack),/Cannot decode/);assert.equal(l.state,state);});
test('edits during async decoding are never overwritten by an older import',async()=>{const l=fixture();let release;l.ctx.decodeAudioData=()=>new Promise(r=>{release=r;});const job=l.importPackage({...pack,bindings:{light:pack.bindings.light},settings:{}});l.setSettings('heavy',{gain:.12});release({duration:1});await assert.rejects(job,/Library changed/);assert.equal(l.state.settings.heavy.gain,.12);assert.equal(l.state.bindings.light,undefined);});

test('additive AI pack cannot replace the preferred bundled punch recordings',async()=>{const l=fixture();await l.addMissingRecordings(pack);assert.equal(l.state.bindings.light,undefined);assert.equal(l.state.bindings.heavy,undefined);assert.equal(l.source('light'),'bundled-recording');});

