import{chromium}from'playwright';import assert from'node:assert/strict';import fs from'node:fs/promises';
const b=await chromium.launch(),p=await b.newPage({viewport:{width:1100,height:800}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:5184/character-foundation.html');await p.waitForFunction(()=>window.FOUNDATION);
for(const [id,options]of Object.entries({hair:['long','mullet','parted','rainbow'],hoodie:['short','long','none'],beltStyle:['plain','utility','sash','double'],auraOrigin:['body','fists','head'],emblemPlacement:['front','back','both','cape','shoeLeft','shoeRight'],footwear:['sandals','shoes','boots']})){for(const value of options){await p.selectOption('#'+id,value);assert.equal(await p.evaluate(id=>FOUNDATION.recipe[id],id),value);}}
await p.selectOption('#costume','roster-warden');const png=await p.evaluate(()=>{const c=document.createElement('canvas');c.width=c.height=128;const x=c.getContext('2d');x.strokeStyle='#54242c';x.lineWidth=8;x.strokeRect(20,12,88,102);for(let i=35;i<110;i+=20){x.beginPath();x.moveTo(i,12);x.lineTo(i,114);x.stroke();}x.lineWidth=5;x.beginPath();x.moveTo(20,62);x.lineTo(108,62);x.stroke();return c.toDataURL();});await fs.mkdir('public/patterns',{recursive:true});await fs.writeFile('public/patterns/warden-bars.png',Buffer.from(png.split(',')[1],'base64'));
await p.locator('#tattooFile').setInputFiles({name:'bars.png',mimeType:'image/png',buffer:Buffer.from(png.split(',')[1],'base64')});await p.waitForFunction(()=>FOUNDATION.recipe.tattooImage);await p.selectOption('#tattooRegion','wholeHead');await p.locator('#pinTattoo').click();assert.equal(await p.evaluate(()=>FOUNDATION.recipe.tattoos.length),1);
await p.evaluate(()=>{const r=FOUNDATION.recipe;r.tattoos.push({...r.tattoos[0],region:'upperArmL'});FOUNDATION.draw();});await p.locator('#view').screenshot({path:'artifacts/warden-tattoo-preview.png'});
const roundtrip=await p.evaluate(async()=>{const{validateModularRecipe}=await import('/src/engine/modular-costume.js');return validateModularRecipe({...FOUNDATION.recipe,schema:1,skeleton:'ual-deform-v1',body:'faceted-v1'});});assert.equal(roundtrip.tattoos.length,2);
await p.selectOption('#costume','roster-rage');assert.equal(await p.evaluate(()=>FOUNDATION.recipe.size),1.25);await p.selectOption('#costume','roster-sol');assert.equal(await p.evaluate(()=>document.querySelector('#size').value),'1');
await p.selectOption('#costume','roster-onyx');await p.selectOption('#aura','sparks');await p.selectOption('#auraOrigin','fists');await p.locator('#view').screenshot({path:'artifacts/onyx-fist-aura-preview.png'});
assert.equal(errors.length,0);console.log({errors,passed:['new hair and wardrobe selectors','all emblem targets','tattoo layers and roundtrip','maximum size reset','glow and fist aura']});await b.close();
