import {Fighter} from '../src/engine/entity.js';import {createSoldierFamilyDefinition} from '../src/data/soldier-family.js';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import * as T from 'three';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';import {mainCombatFixture} from './helpers/main-combat-fixture.mjs';import {loadModularCharacter} from '../src/engine/modular-character.js';
globalThis.ProgressEvent??=class{};
test('shipped Death01 moves through collapse then seeds physical corpse without moving simulation root',async()=>{
 const x=mainCombatFixture();try{const f=new Fighter(createSoldierFamilyDefinition({id:'death-test'}));x.g.entities.push(f);x.g.scene.add(f.obj);f._game=x.g;const b=await fs.readFile('public/models/modular-hero/modular-hero.glb');f.def={...f.def,highwallBiological:true,model:{...f.def.model,body:'faceted-v1'}};const c=await loadModularCharacter(f,{load:()=>new GLTFLoader().parseAsync(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),'')});f.persistCorpse=true;f.noRespawn=true;f._altTag=()=>{};f.vel.set(0,0,0);f._ko();assert.equal(f._deathPresentation.take,'Death01');assert.equal(f.ragdoll,undefined);const root=f.pos.clone(),hips=[];let transitionHead=null,previousHead=null;
 for(let i=0;i<240;i++){const wasSource=!!f._deathPresentation;previousHead=c.actor.getObjectByName('DEF-head').getWorldPosition(new T.Vector3());f.update(1/120,x.g);if(wasSource&&!f._deathPresentation)transitionHead=c.actor.getObjectByName('DEF-head').getWorldPosition(new T.Vector3()).distanceTo(previousHead);if([0,57,114,171].includes(i)){c.actor.updateWorldMatrix(true,true);hips.push(c.actor.getObjectByName('DEF-hips').getWorldPosition(new T.Vector3()).y);}if(f._deathPresentation)assert.ok(f.pos.distanceTo(root)<1e-8);}
 assert.ok(transitionHead<1,'source-to-contact head correction exceeds one world unit');assert.ok(hips[2]<hips[0]-3);assert.equal(f._deathPresentation,null);assert.ok(f.ragdoll);assert.equal(f.alive,false);for(let i=0;i<1200;i++)f.update(1/120,x.g);assert.ok(Math.hypot(f.pos.x-root.x,f.pos.z-root.z)<8,'grounded corpse drifted beyond authored collapse envelope');assert.equal(f.ragdoll.asleep,true,'corpse never settles '+JSON.stringify({ground:f.ragdoll._grounded,still:f.ragdoll._still,points:Object.values(f.ragdoll.P).map(p=>p.pos.distanceTo(p.prev))}));assert.equal(f._remove,undefined);const beforeDrop=f.ragdoll.P.pelvis.pos.y;x.w.heightAt=()=>-30;f.update(1/120,x.g);assert.equal(f.ragdoll.asleep,false,'removed support must wake corpse');for(let i=0;i<240;i++)f.update(1/120,x.g);assert.ok(f.ragdoll.P.pelvis.pos.y<beforeDrop,'corpse stays suspended after floor removal '+JSON.stringify({beforeDrop,y:f.ragdoll.P.pelvis.pos.y,ground:f.ragdoll._grounded,asleep:f.ragdoll.asleep}));
 }finally{x.close();}
});
