import test from 'node:test';
import assert from 'node:assert/strict';
import * as T from 'three';
import {HighwallNavigation} from '../src/engine/highwall-navigation.js';
import {routeHighwallIntent} from '../src/engine/highwall-routing.js';
import {mainCombatFixture} from './helpers/main-combat-fixture.mjs';
const bounds={minX:-40,maxX:80,minZ:-40,maxZ:80};
const shape={radius:2.2,height:12};
function staircase(){const solids=[];for(let i=0;i<5;i++)solids.push({id:'step-'+i,x:0,z:20-i*6,hx:12,hz:3,bottom:0,top:(i+1)*2,standable:true,buildingRole:'step',kind:'step'});solids.push({id:'deck',x:0,z:-16,hx:24,hz:12,bottom:8,top:10,standable:true,kind:'deck'});return solids;}
const ground={x:0,y:0,z:32},deck={x:0,y:10,z:-16};
test('physical treads connect ground to raised floor in both directions and preserve elevation',()=>{const nav=new HighwallNavigation({bounds,solids:staircase()});for(const [a,b]of [[ground,deck],[deck,ground]]){const route=nav.route(a,b,shape);assert.ok(route);assert.equal(route.points.at(-1).y,b.y);for(let i=1;i<route.points.length;i++)assert.ok(nav.walkSegmentClear(route.points[i-1],route.points[i],shape));}});
test('cannot invent a path to disconnected or excessively tall platform',()=>{const nav=new HighwallNavigation({bounds,solids:[staircase().at(-1)]});assert.equal(nav.route(ground,deck,shape),null);assert.equal(nav.walkSegmentClear(ground,deck,shape),false);});
test('headroom blocks stair route for tall actors while shorter actor passes',()=>{const solids=staircase();solids.push({x:0,z:8,hx:18,hz:3,bottom:15,top:18});const nav=new HighwallNavigation({bounds,solids});assert.equal(nav.walkSegmentClear(ground,deck,shape),false);assert.ok(nav.walkSegmentClear(ground,deck,{radius:2.2,height:6}));});
test('a gap on an elevated floor cannot be smoothed into an airborne chord',()=>{const nav=new HighwallNavigation({bounds,solids:[{x:0,z:0,hx:6,hz:8,bottom:8,top:10,standable:true},{x:25,z:0,hx:6,hz:8,bottom:8,top:10,standable:true}]});assert.equal(nav.segmentClear({x:0,y:10,z:0},{x:25,y:10,z:0},shape),false);assert.equal(nav.route({x:0,y:10,z:0},{x:25,y:10,z:0},shape),null);});
test('gate changes invalidate elevated route cache and explicit floor identity',()=>{const solids=staircase(),nav=new HighwallNavigation({bounds,solids});assert.ok(nav.route(ground,deck,shape));nav.replace([...solids,{x:0,z:2,hx:12,hz:3,bottom:0,top:40}],2);assert.equal(nav.walkSegmentClear(ground,deck,shape),false);nav.replace(solids,3);assert.equal(nav.route(ground,deck,shape).revision,3);assert.equal(nav.route(ground,{...deck,y:0},shape),null);});
test('elevated routing steers grounded actor and leaves unsupported or flying motion alone',()=>{const nav=new HighwallNavigation({bounds,solids:staircase()});const f={pos:{...deck},radius:2.2,ai:{}};const it=routeHighwallIntent(nav,f,{move:{x:0,z:0}},.05,ground);assert.ok(it.move.z>0);const air={move:{x:1,z:0}};assert.equal(routeHighwallIntent(nav,{...f,pos:{...deck,y:14}},air,.05,ground),air);assert.equal(routeHighwallIntent(nav,{...f,flying:true},air,.05,ground),air);});
for(const hz of [30,60,120])test(`native fighter climbs and descends authored staircase under route intent at ${hz}Hz`,()=>{const x=mainCombatFixture();try{const solids=staircase().map(p=>({...p,h:p.top,finiteBuilding:true,projectileShape:'box'}));x.w.cover=solids;x.w.coverAll=solids;x.w.ARENA=120;const nav=new HighwallNavigation({bounds,solids});const f=x.p;f._openSky=true;f._altTag=()=>{};f.ai={};f.radius=2.2;f.pos.set(ground.x,ground.y,ground.z);f.obj.position.copy(f.pos);for(const goal of [deck,ground]){delete f._highwallRoute;let arrived=false;for(let i=0;i<hz*12;i++){const dt=1/hz,it=routeHighwallIntent(nav,f,{move:{x:0,z:0}},dt,goal);x.g.time+=dt;x.g.dt=dt;f.move(new T.Vector3(it.move.x,0,it.move.z),dt);f.update(dt,x.g);if(Math.hypot(f.pos.x-goal.x,f.pos.z-goal.z)<3&&Math.abs(f.pos.y-goal.y)<.15){arrived=true;break;}}assert.ok(arrived,JSON.stringify({goal,pos:f.pos.toArray(),route:f._highwallRoute}));}}finally{x.close();}});

test('layered search goes around an upper-floor wall without smoothing through it',()=>{const solids=staircase();solids.push({id:'upper-wall',x:0,z:-12,hx:8,hz:2,bottom:10,top:30});const nav=new HighwallNavigation({bounds,solids});const end={x:0,y:10,z:-24};assert.equal(nav.walkSegmentClear(ground,end,shape),false);const route=nav.route(ground,end,shape);assert.ok(route?.points.length>2,JSON.stringify(route));for(let i=1;i<route.points.length;i++)assert.ok(nav.walkSegmentClear(route.points[i-1],route.points[i],shape));assert.ok(route.points.some(p=>Math.abs(p.x)>10));});
test('support cache distinguishes floors in the same grid column',()=>{const nav=new HighwallNavigation({bounds,solids:[{x:0,z:0,hx:18,hz:18,bottom:20,top:22,standable:true}]});const a={x:-5,y:0,z:0},b={x:5,y:0,z:0};assert.ok(nav.route(a,b,{radius:2,height:12}));assert.ok(nav.route({...a,y:22},{...b,y:22},{radius:2,height:12}));assert.equal(nav.route(a,{...b,y:22},{radius:2,height:12}),null);});

test('current Highwall tower is reached through actual steps by native route intent',async()=>{const {highwallLayout}=await import('../src/data/highwall.js');const l=highwallLayout(),solids=l.pieces,nav=new HighwallNavigation({bounds:l.bounds,solids});const start={x:-28,y:0,z:-154},goal={x:-28,y:48,z:-268};assert.ok(nav.route(start,goal,shape));const x=mainCombatFixture();try{x.w.cover=solids;x.w.coverAll=solids;x.w.ARENA=1100;x.w.heightAt=()=>0;const f=x.p;f._openSky=true;f._altTag=()=>{};f.ai={};f.radius=2.2;f.pos.set(start.x,start.y,start.z);f.obj.position.copy(f.pos);let arrived=false;for(let i=0;i<60*18;i++){const dt=1/60,it=routeHighwallIntent(nav,f,{move:{x:0,z:0}},dt,goal);x.g.time+=dt;x.g.dt=dt;f.move(new T.Vector3(it.move.x,0,it.move.z),dt);f.update(dt,x.g);if(Math.hypot(f.pos.x-goal.x,f.pos.z-goal.z)<3&&Math.abs(f.pos.y-goal.y)<.15){arrived=true;break;}}assert.ok(arrived,JSON.stringify({goal,pos:f.pos.toArray(),route:f._highwallRoute}));}finally{x.close();}});
