import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {mkdir,writeFile} from 'node:fs/promises';
const out='artifacts/progression';await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
try{
 await page.goto('http://127.0.0.1:5180/studio.html?hero=kano');await page.waitForFunction(()=>window.STUDIO?.preview?.fighter);
 await page.evaluate(()=>STUDIO.preview.playing=false);
 await page.getByRole('tab',{name:'Progression',exact:true}).click();
 await page.getByLabel('Q unlock level',{exact:true}).selectOption('4');
 await page.getByRole('button',{name:'Add transformation form',exact:true}).click();
 for(const [label,value] of [['Form level','4'],['Form name','Ascended'],['Form bulk','1.3'],['Form hair color','#ffdc70'],['Form accent','#ffbb32']])await page.getByLabel(label,{exact:true}).fill(value);
 await page.getByLabel('Form costume',{exact:true}).selectOption('plated');
 await page.getByRole('button',{name:'Apply to draft',exact:true}).click();
 assert.equal(await page.locator('dialog').isVisible(),false);
 const identity=await page.evaluate(()=>{const p=STUDIO.preview;window.beforeForm={fighter:p.fighter,obj:p.fighter.obj,pos:p.fighter.pos,slots:p.fighter.slots,ki:p.fighter.ki,name:p.fighter.name};return p.fighter.name;});
 await page.getByLabel('Preview level',{exact:true}).selectOption('4');
 assert.deepEqual(await page.evaluate(()=>{const p=STUDIO.preview,f=p.fighter,b=beforeForm;return {same:f===b.fighter&&f.obj===b.obj&&f.pos===b.pos&&f.slots===b.slots,name:f.name,form:f.formName,bulk:f.def.frame.bulk,costume:f.def.model.costume,accent:f.def.colors.accent};}),{same:true,name:identity,form:'Ascended',bulk:1.3,costume:'plated',accent:'#ffbb32'});
 await page.screenshot({path:`${out}/studio-level4.png`});
 await page.getByLabel('Preview level',{exact:true}).selectOption('1');
 assert.equal(await page.evaluate(()=>STUDIO.preview.fighter.formName),'');
 assert.notEqual(await page.evaluate(()=>STUDIO.preview.fighter.def.model.costume),'plated');
 await page.locator('#state').selectOption('attack');await page.getByLabel('Preview attack',{exact:true}).selectOption('q');
 assert.equal(await page.evaluate(()=>STUDIO.preview.combat.slot),'q');
 const locked=await page.evaluate(()=>{STUDIO.preview.seek(.8);return {phase:STUDIO.preview.combat.phase,shots:STUDIO.preview.combat.game.projectiles.list.length,ki:STUDIO.preview.fighter.ki,max:STUDIO.preview.fighter.maxKi};});
 assert.equal(locked.shots,0);assert.equal(locked.ki,locked.max);assert.match(locked.phase,/locked/);
 await page.getByLabel('Preview level',{exact:true}).selectOption('4');
 assert.ok(await page.evaluate(()=>{STUDIO.preview.seek(.8);return STUDIO.preview.combat.game.projectiles.list.length>0;}));
 const downshift=await page.evaluate(()=>{
  const p=STUDIO.preview,original=p.profile,profile=structuredClone(original);profile.progression.unlocks.lmb=4;
  p.setProfile(p.def,profile);p.setCombat({slot:'lmb'});p.setLevel(4);p.seek(1);
  const before=!!(p.fighter.slots.lmb.charging||p.fighter.slots.lmb.active);p.setLevel(1);
  const result={before,after:!!(p.fighter.slots.lmb.charging||p.fighter.slots.lmb.active),shots:p.combat.game.projectiles.list.length,phase:p.combat.phase};
  p.setProfile(p.def,original);p.setLevel(4);return result;
 });
 assert.deepEqual(downshift,{before:true,after:false,shots:0,phase:'locked-level-4'});
 await page.locator('#save').click();await page.reload();await page.waitForFunction(()=>window.STUDIO?.preview?.fighter);
 await page.evaluate(()=>STUDIO.preview.playing=false);
 assert.deepEqual(await page.evaluate(()=>STUDIO.history.value.progression),{unlocks:{q:4},forms:{4:{name:'Ascended',model:{costume:'plated',hairColor:'#ffdc70'},frame:{bulk:1.3},colors:{accent:'#ffbb32'}}}});
 await page.getByRole('tab',{name:'Progression',exact:true}).click();
 await page.getByRole('button',{name:'Edit level 4 form',exact:true}).click();await page.getByLabel('Form name',{exact:true}).fill('Radiant');await page.getByRole('button',{name:'Apply to draft',exact:true}).click();
 await page.locator('#undo').click();assert.equal(await page.evaluate(()=>STUDIO.history.value.progression.forms[4].name),'Ascended');
 await page.getByRole('button',{name:'Remove level 4 form',exact:true}).click();await page.getByRole('button',{name:'Cancel',exact:true}).click();assert.equal(await page.locator('[data-edit-form="4"]').count(),1);
 await page.setViewportSize({width:390,height:844});await page.getByLabel('Preview level',{exact:true}).selectOption('4');
 await page.screenshot({path:`${out}/studio-mobile.png`,fullPage:true});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 await page.getByRole('button',{name:'Edit level 4 form',exact:true}).click();await page.screenshot({path:`${out}/form-mobile.png`,fullPage:true});await page.getByRole('button',{name:'Cancel',exact:true}).click();
 await page.setViewportSize({width:1440,height:1000});await page.getByRole('button',{name:'Play Test ↗',exact:true}).click();await page.waitForFunction(()=>window.LSW?.game);await page.locator('#pwGo').click();
 const runtime=await page.evaluate(()=>{
  const g=LSW.game,f=g.player;g.update=()=>{};for(const e of g.entities)e.ai=null;
  g.hud.setPlayer(f.def);g.hud.update();const locked=g.hud.slotEls.q.root.classList.contains('locked'),reason=g.hud.slotEls.q.cdn.textContent;
  const identity={obj:f.obj,pos:f.pos,slots:f.slots};f.pos.set(0,140,0);f.vel.set(8,0,60);f.flying=true;f.gait='airborne';
  while(f.level<4)g.levelUp(f,true);g.hud.update();f._animate(1/60);g.world.snapChase();g.world.chase(f,null,1/60);g.world.render();
  return {locked,reason,unlocked:!g.hud.slotEls.q.root.classList.contains('locked'),form:f.formName,costume:f.def.model.costume,same:identity.obj===f.obj&&identity.pos===f.pos&&identity.slots===f.slots,velocity:f.vel.toArray()};
 });
 assert.deepEqual(runtime,{locked:true,reason:'LV 4',unlocked:true,form:'Ascended',costume:'plated',same:true,velocity:[8,0,60]});
 await page.screenshot({path:`${out}/game-level4.png`});
 assert.deepEqual(errors,[]);await writeFile(`${out}/results.json`,JSON.stringify({runtime,errors},null,2));console.log('PASS Studio form authoring, real stable-rig level preview, locked/live attacks, save/reload/undo, mobile and game HUD progression');
}catch(error){await page.screenshot({path:`${out}/failure.png`,fullPage:true}).catch(()=>{});throw error;}finally{await browser.close();}
