import test from 'node:test';
import assert from 'node:assert/strict';
import * as T from 'three';
import {mainCombatFixture} from './helpers/main-combat-fixture.mjs';
import {previewPropThrow} from '../src/engine/thrown-prop-contact.js';
function rock(x,{y=2,z=4,w=.1}={}){const mesh=new T.Mesh(new T.DodecahedronGeometry(2),new T.MeshBasicMaterial());mesh.position.set(0,y,z);x.g.scene.add(mesh);const ref={x:0,z,w,s:2,mesh};x.w.rocks=[ref];return ref;}
test('flying pickup requires actual vertical proximity to prop',()=>{const x=mainCombatFixture();try{const r=rock(x);x.p.pos.y=90;x.p.flying=true;assert.ok(x.g.propInReach(x.p)===null,'must not hoist a ground prop from 90 units above it');x.p.pos.y=7;assert.equal(x.g.propInReach(x.p)?.ref,r,'low flying pickup remains reachable');}finally{x.close();}});
test('lift capacity still rejects a nearby overweight prop',()=>{const x=mainCombatFixture();try{rock(x,{w:1e12});assert.equal(x.g.propInReach(x.p),null);assert.equal(x.p._tooHeavyProp.kind,'rock');}finally{x.close();}});
test('throw and its preview begin at the carried mesh without muzzle teleport',()=>{const x=mainCombatFixture({mode:'powerworld'});try{const r=rock(x);const mesh=r.mesh;mesh.position.set(1,16,2);x.p._carry={kind:'rock',mesh,w:.1,spd:70,ratio:2,size:2};x.p._openSky=true;x.g.heroYell=()=>{};const release=mesh.position.clone(),cue=previewPropThrow(x.p,x.g);assert.ok(cue.points[0].distanceTo(release)<1e-8,'prediction starts at actual payload');x.g.throwProp(x.p);assert.ok(mesh.position.distanceTo(release)<1e-8,'release cannot jump to muzzle');}finally{x.close();}});


test('native low-flight pickup initializes the payload before immediate release',()=>{const x=mainCombatFixture({mode:'powerworld'});try{const r=rock(x);x.p.pos.y=7;x.p.flying=true;x.p._openSky=true;x.g.heroYell=()=>{};assert.equal(x.g.grabProp(x.p),true);const c=x.p._carry;assert.equal(r.carried,true);assert.equal(r.mesh.visible,false);assert.ok(c.mesh.position.distanceTo(r.mesh.position)<1e-8,'reach starts at actual source, not overhead');const release=c.mesh.position.clone();x.g.throwProp(x.p);assert.ok(c.mesh.position.distanceTo(release)<1e-8);assert.equal(x.p._carry,null);}finally{x.close();}});

test('native pickup reaches before lift, then hands off to overhead and interruption drops',()=>{const x=mainCombatFixture({mode:'powerworld'});try{const r=rock(x);x.g.heroYell=()=>{};x.p._openSky=true;assert.ok(x.g.grabProp(x.p));const c=x.p._carry,start=c.mesh.position.clone();x.g.updateCarry(.1*c.pickup.duration);assert.ok(c.mesh.position.distanceTo(start)<1e-8);x.g.updateCarry(.5*c.pickup.duration);assert.ok(c.mesh.position.y>start.y);x.g.updateCarry(2);assert.equal(c.pickup,null);assert.ok(c.mesh.position.y>10); }finally{x.close();}});
test('stun during reach drops current payload without launching it',()=>{const x=mainCombatFixture({mode:'powerworld'});try{rock(x);x.g.heroYell=()=>{};x.p._openSky=true;x.g.grabProp(x.p);const c=x.p._carry,at=c.mesh.position.clone();x.p.stunT=1;x.g.updateCarry(.1);assert.equal(x.p._carry,null);assert.ok(c.mesh.position.distanceTo(at)<1e-8);}finally{x.close();}});
import {beginPropPickup} from '../src/engine/prop-pickup.js';
test('capacity ratio selects progressively longer easy, effort and struggle lifts',()=>{const durations=[8,2,1.1].map(ratio=>{const c={ratio,mesh:new T.Object3D()};beginPropPickup({},c,new T.Vector3());return c.pickup.duration;});assert.deepEqual(durations,[.55,.85,1.2]);});

test('hit stop pauses lift progress and a defeated holder drops the payload',()=>{const x=mainCombatFixture({mode:'powerworld'});try{rock(x);x.g.heroYell=()=>{};x.p._openSky=true;x.g.grabProp(x.p);const c=x.p._carry,at=c.mesh.position.clone();x.p.hitstop=.2;x.g.updateCarry(.1);assert.equal(c.pickup.age,0,'hit stop advanced pickup');assert.ok(c.mesh.position.distanceTo(at)<1e-8);x.p.state='ko';x.g.updateCarry(.1);assert.equal(x.p._carry,null);assert.ok(c.mesh.parent===x.g.scene,'KO must drop, not delete the payload');assert.equal(x.g._flung.length,1);}finally{x.close();}});

test('early-release guide predicts a drop until the payload finishes lifting',()=>{const x=mainCombatFixture({mode:'powerworld'});try{rock(x);x.g.heroYell=()=>{};x.g.grabProp(x.p);const cue=previewPropThrow(x.p,x.g),start=cue.points[0];assert.ok(cue.points.every(p=>Math.abs(p.x-start.x)<1e-8&&Math.abs(p.z-start.z)<1e-8),'unfinished lift advertised a forward throw');}finally{x.close();}});
