import test from 'node:test';import assert from 'node:assert/strict';import {Vector3,Group} from 'three';import {SquadTransport} from '../src/engine/squad-transport.js';
function fixture(){const t=Object.create(SquadTransport.prototype),p={alive:true};Object.assign(t,{state:'parked',model:new Group(),origin:new Vector3(0,0,0),home:new Vector3(),stop:'lab',passengers:new Map([[p,{}]]),manifest:{ramp:{closedAngle:1}},g:{player:p,ms:{squad:{members:[]},convoyOperation:{destination:new Vector3(0,0,600)},threatLab:{clearPad:(x,z)=>new Vector3(x,0,z)}},world:{heightAt:()=>0}},sync(){}});return t;}
test('transport alternates depot and original lab area only after landing',()=>{const t=fixture();assert(t.launch());assert.equal(t.stop,'lab');assert.equal(t.pendingStop,'depot');assert.deepEqual(t.to.toArray(),[70,0,600]);t.update(1.2);t.update(t.duration);t.update(1.2);assert.equal(t.stop,'depot');assert.equal(t.state,'parked');assert(t.launch());assert.equal(t.pendingStop,'lab');assert.deepEqual(t.to.toArray(),[0,0,0]);t.update(1.2);t.update(t.duration);t.update(1.2);assert.equal(t.stop,'lab');assert.deepEqual(t.origin.toArray(),[0,0,0]);});
test('failed return pad search does not consume destination or depart',()=>{const t=fixture();t.stop='depot';t.g.ms.threatLab.clearPad=()=>null;assert(!t.launch());assert.equal(t.stop,'depot');assert.equal(t.state,'parked');});
test('route still refuses missing passengers and airborne departures',()=>{const t=fixture();t.g.ms.squad.members=[{alive:true}];assert(!t.launch());t.g.ms.squad.members=[];t.state='flying';assert(!t.launch());});

test('return landing turns the ramp toward the lab during descent',()=>{const t=fixture();t.stop='depot';t.model.position.set(70,0,600);t.g.pwStage={researchLab:{site:{x:0,z:-100}}};assert(t.launch());t.update(1.2);t.update(t.duration*.5);assert.equal(t.model.rotation.y,t.travelYaw);t.update(t.duration*.5);assert(Math.abs(Math.atan2(Math.sin(t.model.rotation.y-Math.PI),Math.cos(t.model.rotation.y-Math.PI)))<1e-8);});

test('seat cycling swaps occupants without ejecting or duplicating them',()=>{const t=fixture(),p=t.g.player,ally={alive:true},a={id:'passenger'},b={id:'pilot',role:'pilot'};t.manifest.seats=[a,b];t.passengers=new Map([[p,a],[ally,b]]);assert(t.cycleSeat(p));assert.equal(t.passengers.get(p),b);assert.equal(t.passengers.get(ally),a);assert.equal(t.passengers.size,2);t.state='flying';assert(t.cycleSeat(p));assert.equal(t.passengers.get(p),a);assert(!t.cycleSeat({alive:true}));t.state='destroyed';assert(!t.cycleSeat(p));});
