const fs=require('fs');const edit=(p,f)=>fs.writeFileSync(p,f(fs.readFileSync(p,'utf8')));
const select=(id,label,values)=>`<label>${label}<select id="${id}">${values.map(v=>`<option value="${v}">${v}</option>`).join('')}</select></label>`;
const extra=select('hoodie','Hoodie sleeves',['none','short','long'])+select('handModule','Right hand module',['none','cannon'])+select('auraOrigin','Aura origin',['body','fists','head'])+select('glowRegion','Glowing material',['none','trim','suit','accent'])+'<label>Glow strength<input id="glowStrength" type="range" min="0" max="3" step=".1"></label><label>Bust contour<input id="bust" type="range" min="0" max="1" step=".1"></label><label>Emblem size<input id="emblemScale" type="range" min=".4" max="1.8" step=".1"></label><label><input id="mustache" type="checkbox">Mustache</label><label><input id="unlitBlack" type="checkbox">Absolute black for #000000 surfaces</label><button id="pinTattoo">Keep tattoo as a layer</button><button id="clearTattooLayers">Remove saved tattoo layers</button><small id="tattooLayersStatus">Up to eight saved layers plus the current preview</small>';
edit('character-foundation.html',s=>s.replace('<hr><h2>Motion review',extra+'<hr><h2>Motion review').replace('<option value="utility">','<option value="sash">Sash</option><option value="double">Double strap</option><option value="utility">').replace('<option value="shoes">','<option value="sandals">Sandals</option><option value="shoes">').replace('<option value="both">','<option value="cape">Cape</option><option value="shoeLeft">Left shoe</option><option value="shoeRight">Right shoe</option><option value="both">').replace('<option value="chest">Chest</option>','<option value="face">Face</option><option value="wholeHead">Whole head</option><option value="headBack">Back of head</option><option value="headLeft">Left head</option><option value="headRight">Right head</option><option value="chest">Chest</option>').replace('<option value="boots">Boots</option></select></label><label>Region color','<option value="boots">Boots</option>'+['shoes','forearms','shoulders','gauntlets','cape','coat','belt','vest','backpack'].map(x=>`<option value="${x}">${x}</option>`).join('')+'</select></label><label>Region color'));
edit('src/tool/character-foundation.js',s=>s.replace(" if(sync){"," if(sync){").replace("  for(const [id,key]of Object.entries(colorFields))","  for(const key of ['bust','emblemScale','glowStrength'])document.getElementById(key).value=recipe[key]??(key==='bust'?(recipe.anatomy==='female'?.45:0):1);\n  for(const [id,key]of Object.entries(colorFields))").replace("document.querySelector('#muscle').oninput",`for(const key of ['bust','emblemScale','glowStrength'])document.getElementById(key).oninput=e=>{recipe[key]=+e.target.value;applyRecipe();draw();};
 document.querySelector('#pinTattoo').onclick=()=>{if(!recipe.tattooImage)return;recipe.tattoos=recipe.tattoos||[];if(recipe.tattoos.length>=8){document.querySelector('#tattooLayersStatus').textContent='Eight layers maximum';return;}recipe.tattoos.push({image:recipe.tattooImage,region:recipe.tattooRegion||'upperArmL',scale:1});delete recipe.tattooImage;document.querySelector('#tattooLayersStatus').textContent=recipe.tattoos.length+' layers saved';draw();};
 document.querySelector('#clearTattooLayers').onclick=()=>{recipe.tattoos=[];document.querySelector('#tattooLayersStatus').textContent='Saved layers removed';draw();};
 document.querySelector('#muscle').oninput`).replace('file.size>3200000','file.size>14000000'));
edit('src/data/hero-signature-recipes.js',s=>{const at=s.indexOf('export const HERO_SIGNATURE_RECIPES');return s.slice(0,at)+`// Approved direction follow-up; all fields remain editable creator modules.
const previousStefanos={...directions.stefanos};
Object.assign(directions, Object.fromEntries(Object.entries({
 breach:{frame:'machine',primary:'#778c9b',secondary:'#172b3c',trim:'#121719',metallic:true,armor:false,headwear:'helmet',handModule:'cannon',shield:true,shieldStyle:'riot'},
 ironclad:{centerPanel:true,secondary:'#bb7838',regionColors:{arms:'#455d71',legs:'#2b3c4b'}},
 foundry:{metallic:false,hoodie:'short',primary:'#673f35',secondary:'#d4a461',trim:'#21252b',pattern:'denim',patternRegion:'legs',bareArms:true,belt:true,beltStyle:'utility'},
 sol:{hair:'mullet'},ripclaw:{hoodie:'short',hair:'mohawk',primary:'#465961',secondary:'#b95244',trim:'#192930',pattern:'denim',patternRegion:'legs',bareArms:true},
 rage:{frame:'heavy',size:1.25,muscle:1.3,hair:'none'},onyx:{trim:'#000000',secondary:'#48cbd2',glowRegion:'accent',glowStrength:1.5,unlitBlack:true},
 nova:{hair:'parted',hairColor:'#edc87b'},knightfall:{cape:false},
 stefanos:{coat:true,coatStyle:'short',primary:'#242b35',secondary:'#dedfd5',pattern:'solid',regionColors:{legs:'#242b35',calves:'#242b35'},footwear:'shoes',mustache:true,beard:true},
 ramiro:{mustache:true},jawah:{mustache:true},kamaria:{hair:'long'},
 }).map(([id,r])=>[id,{...directions[id],...r}])));
directions.warden={...directions.warden,bareArms:true};
// Preserve the previous pinstripe uniform as a separate reusable costume.
`+s.slice(at).replace("HERO_SIGNATURE_RECIPES.deck52=","HERO_SIGNATURE_RECIPES.deck52=");});
