const fs=require('fs');const edit=(p,f)=>fs.writeFileSync(p,f(fs.readFileSync(p,'utf8')));
edit('src/engine/modular-signature-parts.js',s=>s.replace("mat(i%2?'#e0dbcb':'#fff1d7')","mat(i%2?'#e7eaf0':'#ffffff')"));
edit('src/engine/modular-costume.js',s=>s.replace("'axe','spear']","'axe','spear','dualKatana']").replace("'pinstripe','custom']","'pinstripe','denim','custom']"));
edit('src/engine/modular-surfaces.js',s=>s.replace("}else if(recipe.pattern==='stripes'","}else if(recipe.pattern==='denim'){const c=document.createElement('canvas');c.width=c.height=256;const x=c.getContext('2d');x.fillStyle='#294762';x.fillRect(0,0,256,256);x.strokeStyle='#41617a';x.lineWidth=1;for(let i=-256;i<512;i+=4){x.beginPath();x.moveTo(i,0);x.lineTo(i+256,256);x.stroke();}t=new T.CanvasTexture(c);\n }else if(recipe.pattern==='stripes'"));
edit('src/engine/modular-weapon-preview.js',s=>s.replace("none:Object.freeze", "dualKatana:Object.freeze({label:'Dual katana grip preview',clips:['Sword_Idle'],gaps:['Dedicated dual wield attack animation']}),\n  none:Object.freeze").replace("const spear=weapons.spear;",`const dual=new T.Group();right.add(dual);weapons.dualKatana=dual;const off=new T.Group();left.add(off);for(const group of [dual,off]){group.position.set(0,.075,.028);group.rotation.x=Math.PI/2;mesh(group,new T.CylinderGeometry(.018,.018,.20,6),dark);mesh(group,new T.BoxGeometry(.10,.02,.065),gold,0,.11);const shape=new T.Shape();shape.moveTo(-.018,.12);shape.lineTo(.018,.12);shape.quadraticCurveTo(.025,.66,.11,.91);shape.lineTo(.065,.86);shape.quadraticCurveTo(-.016,.60,-.018,.12);mesh(group,new T.ExtrudeGeometry(shape,{depth:.012,bevelEnabled:false}),steel,0,0,-.006);}dual.userData.clipFamily=MODULAR_WEAPON_CLIP_FAMILIES.dualKatana;
  const spear=weapons.spear;`).replace('shield.visible=state.shield;','off.visible=state.weapon===\'dualKatana\';shield.visible=state.shield&&!off.visible;').replace('for(const group of [...Object.values(weapons),shield])','for(const group of [...Object.values(weapons),shield,off])'));
edit('character-foundation.html',s=>s.replace('<option value="axe">Axe</option>','<option value="axe">Axe</option><option value="dualKatana">Dual katanas · grip preview</option>').replace('<option value="gilt">','<option value="denim">Denim weave</option><option value="gilt">').replace('<label>Aura<select','<label><input id="skirt" type="checkbox">Short skirt</label><label>Aura<select'));
edit('src/tool/character-foundation.js',s=>s.replace("['beard',","['skirt','beard',"));
edit('src/data/hero-signature-recipes.js',s=>s.replace("knightfall:{","knightfall:{weapon:'dualKatana',beltStyle:'plain',emblemColor:'#758193',").replace("merc:{","merc:{pattern:'denim',patternRegion:'legs',"));
